import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  curriculumSidebar: [
    {
      type: 'category',
      label: 'Curriculum Overview',
      items: ['curriculum/index'],
    },
    {
      type: 'category',
      label: 'Arc 1: Foundations',
      items: [
        'curriculum/week-1/index',
        'curriculum/week-1/quiz',
      ],
    },
    {
      type: 'category',
      label: 'Arc 2: 2D Game',
      items: [
        'curriculum/week-2/index',
        'curriculum/week-2/quiz',
        'curriculum/week-3/index',
        'curriculum/week-3/quiz',
        'curriculum/week-4/index',
        'curriculum/week-4/quiz',
      ],
    },
    {
      type: 'category',
      label: 'Arc 3: 3D Game',
      items: [
        'curriculum/week-5/index',
        'curriculum/week-5/quiz',
        'curriculum/week-6/index',
        'curriculum/week-6/quiz',
        'curriculum/week-7/index',
        'curriculum/week-7/quiz',
      ],
    },
    {
      type: 'category',
      label: 'Demo Day',
      items: [
        'curriculum/week-8/index',
      ],
    },
  ],
  worksheetsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'worksheets',
    },
  ],
  resourcesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'resources',
    },
  ],
};

export default sidebars;
