#!/usr/bin/env node

/**
 * Level compiler: transforms level.json into GDevelop game.json.
 *
 * Usage: node compile-level.mjs [level.json] [game.json]
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Minimap config (generated by generate-minimap.mjs)
const minimapConfigPath = join(__dirname, 'minimap-config.json');
const MINIMAP = existsSync(minimapConfigPath)
  ? JSON.parse(readFileSync(minimapConfigPath, 'utf8'))
  : null;

// ─── Load & validate level ───────────────────────────────────────────────

function loadLevel(path) {
  const level = JSON.parse(readFileSync(path, 'utf8'));
  validate(level);
  return level;
}

function validate(level) {
  const { grid, areas, spawn } = level;
  if (!grid || !grid.length) throw new Error('Grid is empty');

  const width = grid[0].length;
  for (let r = 0; r < grid.length; r++) {
    if (grid[r].length !== width)
      throw new Error(`Grid row ${r} has length ${grid[r].length}, expected ${width}`);
  }

  // Check borders are solid
  for (let c = 0; c < width; c++) {
    if (grid[0][c] !== '#') throw new Error(`Top border not solid at col ${c}`);
    if (grid[grid.length - 1][c] !== '#') throw new Error(`Bottom border not solid at col ${c}`);
  }
  for (let r = 0; r < grid.length; r++) {
    if (grid[r][0] !== '#') throw new Error(`Left border not solid at row ${r}`);
    if (grid[r][width - 1] !== '#') throw new Error(`Right border not solid at row ${r}`);
  }

  // Check all area characters are defined
  for (let r = 0; r < grid.length; r++) {
    for (let c = 0; c < width; c++) {
      const ch = grid[r][c];
      if (ch !== '#' && !areas[ch])
        throw new Error(`Grid char '${ch}' at (${r},${c}) not defined in areas`);
    }
  }

  // Check spawn is on open cell
  const sr = Math.floor(spawn.gy);
  const sc = Math.floor(spawn.gx);
  if (grid[sr]?.[sc] === '#')
    throw new Error(`Spawn at (${spawn.gx},${spawn.gy}) is inside a wall`);
}

// ─── Geometry generation ─────────────────────────────────────────────────

function isOpen(grid, r, c) {
  return r >= 0 && r < grid.length && c >= 0 && c < grid[0].length && grid[r][c] !== '#';
}

function getFloorHeight(level, r, c) {
  const ch = level.grid[r][c];
  const area = level.areas[ch];
  const baseHeight = area?.floorHeight || 0;
  if (level.heights && level.heights[r] && level.heights[r][c] !== undefined) {
    return baseHeight + level.heights[r][c];
  }
  return baseHeight;
}

function getCeilingHeight(level, r, c) {
  const ch = level.grid[r][c];
  const area = level.areas[ch];
  return area?.ceilingHeight || level.settings.wallHeight;
}

function getMaterial(level, r, c) {
  const ch = level.grid[r][c];
  const area = level.areas[ch];
  const matName = area?.material || 'dungeon';
  return level.materials[matName];
}

/**
 * Generate all geometry instances from the grid.
 *
 * Coordinate convention (matching GDevelop Physics3D / Jolt):
 *   X = left/right (grid columns)
 *   Y = forward/back (grid rows)
 *   Z = up/down (vertical — gravity pulls -Z)
 *
 * GDevelop object properties:
 *   width  = X extent
 *   height = Y extent
 *   depth  = Z extent (vertical)
 */
function generateGeometry(level) {
  const { grid, settings } = level;
  const cs = settings.cellSize;
  const wt = settings.wallThickness;
  const rows = grid.length;
  const cols = grid[0].length;
  const instances = [];
  let uid = 0;

  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      if (!isOpen(grid, r, c)) continue;

      const mat = getMaterial(level, r, c);
      const floorH = getFloorHeight(level, r, c);
      const ceilH = getCeilingHeight(level, r, c);
      const wallH = ceilH - floorH;

      // Floor slab (thin horizontal at floor level)
      instances.push({
        type: 'floor', id: `floor-${uid++}`,
        x: c * cs, y: r * cs, z: floorH,
        width: cs, height: cs, depth: wt,
        texture: mat.floor,
        materialType: mat.materialType,
      });

      // Ceiling slab (thin horizontal at ceiling level)
      instances.push({
        type: 'ceiling', id: `ceil-${uid++}`,
        x: c * cs, y: r * cs, z: floorH + wallH,
        width: cs, height: cs, depth: wt,
        texture: mat.ceiling,
        materialType: mat.materialType,
      });

      // North wall (border with r-1): thin in Y, tall in Z
      if (!isOpen(grid, r - 1, c)) {
        instances.push({
          type: 'wall', id: `wall-${uid++}`,
          x: c * cs, y: r * cs, z: floorH,
          width: cs, height: wt, depth: wallH,
          texture: mat.wall, materialType: mat.materialType,
        });
      }

      // South wall (border with r+1)
      if (!isOpen(grid, r + 1, c)) {
        instances.push({
          type: 'wall', id: `wall-${uid++}`,
          x: c * cs, y: (r + 1) * cs - wt, z: floorH,
          width: cs, height: wt, depth: wallH,
          texture: mat.wall, materialType: mat.materialType,
        });
      }

      // West wall (border with c-1): thin in X, tall in Z
      if (!isOpen(grid, r, c - 1)) {
        instances.push({
          type: 'wall', id: `wall-${uid++}`,
          x: c * cs, y: r * cs, z: floorH,
          width: wt, height: cs, depth: wallH,
          texture: mat.wall, materialType: mat.materialType,
        });
      }

      // East wall (border with c+1)
      if (!isOpen(grid, r, c + 1)) {
        instances.push({
          type: 'wall', id: `wall-${uid++}`,
          x: (c + 1) * cs - wt, y: r * cs, z: floorH,
          width: wt, height: cs, depth: wallH,
          texture: mat.wall, materialType: mat.materialType,
        });
      }

      // Note: height transitions between adjacent cells are handled by the
      // character controller's stairHeightMax — no step walls needed.
    }
  }

  return instances;
}

// ─── Object definitions ──────────────────────────────────────────────────

function makeStaticPhysicsBody() {
  return {
    name: 'Physics3D',
    type: 'Physics3D::Physics3DBehavior',
    content: {
      object3D: '',
      bodyType: 'Static',
      bullet: false,
      fixedRotation: false,
      shape: 'Box',
      meshShapeResourceName: '',
      shapeOrientation: 'Z',
      shapeDimensionA: 0, shapeDimensionB: 0, shapeDimensionC: 0,
      shapeOffsetX: 0, shapeOffsetY: 0, shapeOffsetZ: 0,
      massCenterOffsetX: 0, massCenterOffsetY: 0, massCenterOffsetZ: 0,
      massOverride: 0,
      density: 1.0,
      friction: 0.5,
      restitution: 0.0,
      linearDamping: 0.1,
      angularDamping: 0.1,
      gravityScale: 1,
      layers: 17,
      masks: 17,
    },
  };
}

function makeWallObject(textureName, materialType) {
  return {
    assetStoreId: '', name: `Wall_${textureName}`, type: 'Scene3D::Cube3DObject',
    updateIfNotVisible: false, variables: [], effects: [],
    behaviors: [makeStaticPhysicsBody()],
    content: {
      width: 100, height: 100, depth: 100,
      ...makeCubeFaces(textureName),
      enableTextureTransparency: false,
      materialType: materialType || 'StandardWithoutMetalness',
    },
  };
}

function makeFloorObject(textureName, materialType) {
  return {
    assetStoreId: '', name: `Floor_${textureName}`, type: 'Scene3D::Cube3DObject',
    updateIfNotVisible: false, variables: [], effects: [],
    behaviors: [makeStaticPhysicsBody()],
    content: {
      width: 100, height: 100, depth: 100,
      ...makeCubeFaces(textureName),
      enableTextureTransparency: false,
      materialType: materialType || 'StandardWithoutMetalness',
    },
  };
}

function makeCeilingObject(textureName, materialType) {
  return {
    assetStoreId: '', name: `Ceiling_${textureName}`, type: 'Scene3D::Cube3DObject',
    updateIfNotVisible: false, variables: [], effects: [],
    behaviors: [makeStaticPhysicsBody()],
    content: {
      width: 100, height: 100, depth: 100,
      ...makeCubeFaces(textureName),
      enableTextureTransparency: false,
      materialType: materialType || 'StandardWithoutMetalness',
    },
  };
}

function makeCubeFaces(textureName) {
  const faces = {};
  for (const face of ['front', 'back', 'left', 'right', 'top', 'bottom']) {
    faces[`${face}FaceResourceName`] = `${textureName}.png`;
    faces[`${face}FaceVisible`] = true;
    faces[`${face}FaceResourceRepeat`] = true;
  }
  return faces;
}

function makePlayerObject(settings) {
  return {
    assetStoreId: '', name: 'Player', type: 'Scene3D::Cube3DObject',
    updateIfNotVisible: false, variables: [], effects: [],
    behaviors: [
      {
        name: 'Physics3D',
        type: 'Physics3D::Physics3DBehavior',
        content: {
          object3D: '',
          bodyType: 'Dynamic',
          bullet: false,
          fixedRotation: true,
          shape: 'Capsule',
          meshShapeResourceName: '',
          shapeOrientation: 'Z',
          shapeDimensionA: 0, shapeDimensionB: 0, shapeDimensionC: 0,
          shapeOffsetX: 0, shapeOffsetY: 0, shapeOffsetZ: 0,
          massCenterOffsetX: 0, massCenterOffsetY: 0, massCenterOffsetZ: 0,
          massOverride: 0,
          density: 1.0,
          friction: 0.5,
          restitution: 0.0,
          linearDamping: 0.1,
          angularDamping: 0.1,
          gravityScale: 1,
          layers: 17,
          masks: 17,
        },
      },
      {
        name: 'PhysicsCharacter3D',
        type: 'Physics3D::PhysicsCharacter3D',
        content: {
          physics3D: 'Physics3D',
          jumpHeight: settings.jumpSpeed || 150,
          jumpSustainTime: 0.2,
          gravity: settings.gravity || 800,
          fallingSpeedMax: 700,
          forwardAcceleration: 1200,
          forwardDeceleration: 1200,
          forwardSpeedMax: settings.moveSpeed || 200,
          sidewaysAcceleration: 800,
          sidewaysDeceleration: 800,
          sidewaysSpeedMax: settings.strafeSpeed || 150,
          slopeMaxAngle: 50,
          stairHeightMax: settings.stepHeight || 60,
          shouldBindObjectAndForwardAngle: false,
          canBePushed: false,
        },
      },
    ],
    content: {
      width: 30, height: 30, depth: 120,
      frontFaceResourceName: '', backFaceResourceName: '',
      leftFaceResourceName: '', rightFaceResourceName: '',
      topFaceResourceName: '', bottomFaceResourceName: '',
      frontFaceVisible: false, backFaceVisible: false,
      leftFaceVisible: false, rightFaceVisible: false,
      topFaceVisible: false, bottomFaceVisible: false,
      frontFaceResourceRepeat: false, backFaceResourceRepeat: false,
      leftFaceResourceRepeat: false, rightFaceResourceRepeat: false,
      topFaceResourceRepeat: false, bottomFaceResourceRepeat: false,
      enableTextureTransparency: false,
      materialType: 'Basic',
    },
  };
}

function makeHUDObject() {
  return {
    assetStoreId: '', name: 'HUD', type: 'TextObject::Text',
    updateIfNotVisible: false, variables: [], effects: [], behaviors: [],
    characterSize: 24, font: '', textAlignment: 'left',
    color: { b: 255, g: 255, r: 255 }, string: 'Gems: 0',
    bold: true, italic: false, underlined: false, smoothed: true,
    isOutlineEnabled: true, outlineColor: { b: 0, g: 0, r: 0 }, outlineThickness: 2,
    isShadowEnabled: false, shadowColor: { b: 0, g: 0, r: 0 },
    shadowOpacity: 127, shadowDistance: 1, shadowAngle: 90, shadowBlurRadius: 1,
  };
}

function makeGemObject() {
  return {
    assetStoreId: '', name: 'Gem', type: 'Sprite',
    updateIfNotVisible: false, variables: [], effects: [], behaviors: [],
    animations: [{
      name: 'idle', useMultipleDirections: false,
      directions: [{
        looping: true, timeBetweenFrames: 0.08,
        sprites: [{
          hasCustomCollisionMask: false, image: 'gem.png',
          points: [],
          originPoint: { name: 'origine', x: 0, y: 0 },
          centerPoint: { automatic: true, name: 'centre', x: 0, y: 0 },
          customCollisionMask: [],
        }],
      }],
    }],
  };
}

function makeKeyObject() {
  return {
    assetStoreId: '', name: 'Key', type: 'Sprite',
    updateIfNotVisible: false, variables: [], effects: [], behaviors: [],
    animations: [{
      name: 'idle', useMultipleDirections: false,
      directions: [{
        looping: true, timeBetweenFrames: 0.08,
        sprites: [{
          hasCustomCollisionMask: false, image: 'key.png',
          points: [],
          originPoint: { name: 'origine', x: 0, y: 0 },
          centerPoint: { automatic: true, name: 'centre', x: 0, y: 0 },
          customCollisionMask: [],
        }],
      }],
    }],
  };
}

/** Locked door slab — static physics body the combat JS can delete. */
function makeDoorObject() {
  return {
    assetStoreId: '', name: 'Door', type: 'Scene3D::Cube3DObject',
    updateIfNotVisible: false, variables: [], effects: [],
    behaviors: [makeStaticPhysicsBody()],
    content: {
      width: 180, height: 24, depth: 220,
      frontFaceResourceName: 'metal_wall.png',
      backFaceResourceName: 'metal_wall.png',
      leftFaceResourceName: 'metal_wall.png',
      rightFaceResourceName: 'metal_wall.png',
      topFaceResourceName: 'metal_wall.png',
      bottomFaceResourceName: 'metal_wall.png',
      frontFaceVisible: true, backFaceVisible: true,
      leftFaceVisible: true, rightFaceVisible: true,
      topFaceVisible: true, bottomFaceVisible: true,
      frontFaceResourceRepeat: true, backFaceResourceRepeat: true,
      leftFaceResourceRepeat: true, rightFaceResourceRepeat: true,
      topFaceResourceRepeat: true, bottomFaceResourceRepeat: true,
      enableTextureTransparency: false,
      materialType: 'StandardWithoutMetalness',
    },
  };
}

/** Enemy Model3D — NO static physics so JS AI can move them freely. */
function makeEnemyModelObject(name, glbFile) {
  return makeModel3DObject(name, glbFile, 'KeepOriginal', {
    rotationX: 90,
    castShadow: true,
  });
}

/**
 * Build open-cell walkability set + enemy defaults for the combat JsCode.
 */
function buildOpenCellSet(level) {
  const open = [];
  const { grid } = level;
  for (let r = 0; r < grid.length; r++) {
    for (let c = 0; c < grid[0].length; c++) {
      if (grid[r][c] !== '#') open.push(`${c},${r}`);
    }
  }
  return open;
}

function enemyObjectName(type) {
  return capitalize(String(type || 'enemy').toLowerCase());
}

/**
 * Giant Wolfenstein-style combat / AI / HUD / juice runtime (JsCode).
 * Prefer raw Audio() so we don't fight the GDevelop resource pipeline.
 */
function generateCombatJs(level) {
  const s = level.settings || {};
  const cs = s.cellSize || 200;
  const maxHp = s.playerMaxHp || 100;
  const fireCd = s.fireCooldown || 0.35;
  const gunRange = s.gunRange || 800;
  const gunDamage = s.gunDamage || 25;
  const totalGems = (level.collectibles || []).filter(c => c.type === 'gem').length;
  const openCells = buildOpenCellSet(level);

  // Enemy spawn metadata keyed later by instance order per type
  const enemies = (level.enemies || []).map((e, i) => ({
    id: i,
    type: enemyObjectName(e.type),
    gx: e.gx,
    gy: e.gy,
    hp: e.hp ?? 40,
    speed: e.speed ?? 70,
    aggro: e.aggro ?? 500,
    damage: e.damage ?? 10,
    meleeRange: e.meleeRange ?? 70,
    float: !!e.float || e.type === 'beholder',
    boss: !!e.boss,
    roar: !!e.roar || e.type === 'beholder',
    baseZ: e.baseZ ?? (e.type === 'beholder' ? 70 : 0),
  }));

  // JSON embedded into JS (safe — numbers/bools/strings only)
  const enemiesJson = JSON.stringify(enemies);
  const openJson = JSON.stringify(openCells);

  // NOTE: this string is injected as GDevelop inlineCode. Keep it ES5-ish.
  return `
// ── Maze Explorer combat / AI / HUD ──────────────────────────────────
var dt = runtimeScene.getTimeManager().getElapsedTime() / 1000;
if (dt > 0.1) dt = 0.1;
if (!runtimeScene.__fps) {
  var openList = ${openJson};
  var openMap = {};
  for (var oi = 0; oi < openList.length; oi++) openMap[openList[oi]] = true;
  runtimeScene.__fps = {
    hp: ${maxHp},
    maxHp: ${maxHp},
    dead: false,
    won: false,
    gems: 0,
    totalGems: ${totalGems},
    keys: 0,
    score: 0,
    fireCd: 0,
    hurtFlash: 0,
    muzzle: 0,
    shake: 0,
    time: 0,
    roarCd: 3,
    open: openMap,
    cs: ${cs},
    gunRange: ${gunRange},
    gunDamage: ${gunDamage},
    fireCooldown: ${fireCd},
    enemies: ${enemiesJson},
    enemyState: {},
    particles: [],
    audio: {},
    hudReady: false,
    musicStarted: false,
    doorOpen: {},
  };
  // Bind each enemy instance to the nearest unused spawn def of the same type
  var usedDef = {};
  var typeNames = {};
  for (var ei = 0; ei < runtimeScene.__fps.enemies.length; ei++) {
    typeNames[runtimeScene.__fps.enemies[ei].type] = true;
  }
  var bindIdx = 0;
  for (var tName in typeNames) {
    if (!typeNames.hasOwnProperty(tName)) continue;
    var objs = runtimeScene.getObjects(tName) || [];
    for (var j = 0; j < objs.length; j++) {
      var ox = objs[j].getCenterX ? objs[j].getCenterX() : (objs[j].getX() + objs[j].getWidth() / 2);
      var oy = objs[j].getCenterY ? objs[j].getCenterY() : (objs[j].getY() + objs[j].getHeight() / 2);
      var bestDi = -1, bestD = 1e15;
      for (var di = 0; di < runtimeScene.__fps.enemies.length; di++) {
        if (usedDef[di]) continue;
        var d0 = runtimeScene.__fps.enemies[di];
        if (d0.type !== tName) continue;
        var ddx = d0.gx * ${cs} - ox;
        var ddy = d0.gy * ${cs} - oy;
        var dd = ddx * ddx + ddy * ddy;
        if (dd < bestD) { bestD = dd; bestDi = di; }
      }
      if (bestDi < 0) continue;
      usedDef[bestDi] = true;
      var def = runtimeScene.__fps.enemies[bestDi];
      var id = tName + '_' + (bindIdx++);
      objs[j].__enemyId = id;
      runtimeScene.__fps.enemyState[id] = {
        def: def,
        hp: def.hp,
        alive: true,
        obj: objs[j],
        cx: def.gx * ${cs},
        cy: def.gy * ${cs},
        wz: def.baseZ || 0,
        atkCd: 0,
        flash: 0,
        wanderT: Math.random() * 3,
        wdx: (Math.random() - 0.5),
        wdy: (Math.random() - 0.5),
        bobPhase: Math.random() * Math.PI * 2,
      };
    }
  }
}

var F = runtimeScene.__fps;
F.time += dt;
if (F.fireCd > 0) F.fireCd -= dt;
if (F.hurtFlash > 0) F.hurtFlash -= dt;
if (F.muzzle > 0) F.muzzle -= dt;
if (F.shake > 0) F.shake -= dt;
if (F.roarCd > 0) F.roarCd -= dt;

function fpsSfx(name, vol) {
  try {
    if (!F.audio[name]) {
      F.audio[name] = new Audio('./sfx/' + name + '.mp3');
      F.audio[name].preload = 'auto';
    }
    var a = F.audio[name].cloneNode();
    a.volume = vol == null ? 0.55 : vol;
    var p = a.play();
    if (p && p.catch) p.catch(function(){});
  } catch (e) {}
}

function fpsEnsureHud() {
  if (F.hudReady) return;
  F.hudReady = true;
  var root = document.createElement('div');
  root.id = 'maze-fps-hud';
  root.innerHTML = [
    '<div id="maze-crosshair"></div>',
    '<div id="maze-muzzle"></div>',
    '<div id="maze-hurt"></div>',
    '<div id="maze-hud-panel">',
    '  <div id="maze-hp-wrap"><div id="maze-hp-bar"></div></div>',
    '  <div id="maze-hud-text"></div>',
    '</div>',
    '<div id="maze-banner"></div>'
  ].join('');
  var st = document.createElement('style');
  st.textContent = [
    '#maze-fps-hud{position:fixed;inset:0;pointer-events:none;z-index:9000;font-family:ui-monospace,Menlo,Consolas,monospace;color:#fff;}',
    '#maze-crosshair{position:absolute;left:50%;top:50%;width:18px;height:18px;margin:-9px 0 0 -9px;}',
    '#maze-crosshair:before,#maze-crosshair:after{content:"";position:absolute;background:rgba(255,255,255,0.85);box-shadow:0 0 4px #000;}',
    '#maze-crosshair:before{left:8px;top:0;width:2px;height:18px;}',
    '#maze-crosshair:after{left:0;top:8px;width:18px;height:2px;}',
    '#maze-muzzle{position:absolute;left:50%;top:50%;width:120px;height:120px;margin:-40px 0 0 -60px;border-radius:50%;',
    '  background:radial-gradient(circle,rgba(255,220,80,0.85) 0%,rgba(255,120,0,0.35) 40%,transparent 70%);',
    '  opacity:0;transform:scale(0.4);}',
    '#maze-hurt{position:absolute;inset:0;background:radial-gradient(circle,transparent 40%,rgba(160,0,0,0.55) 100%);opacity:0;transition:opacity 0.05s;}',
    '#maze-hud-panel{position:absolute;left:14px;top:14px;min-width:220px;padding:10px 12px;background:rgba(0,0,0,0.45);',
    '  border:1px solid rgba(255,80,160,0.45);border-radius:8px;text-shadow:0 2px 4px #000;}',
    '#maze-hp-wrap{height:14px;background:#300;border:1px solid #811;border-radius:4px;overflow:hidden;margin-bottom:6px;}',
    '#maze-hp-bar{height:100%;width:100%;background:linear-gradient(90deg,#e22,#f84);transition:width 0.12s;}',
    '#maze-hud-text{font-size:13px;line-height:1.45;letter-spacing:0.04em;}',
    '#maze-banner{position:absolute;left:50%;top:40%;transform:translate(-50%,-50%);font-size:clamp(1.4rem,4vw,2.6rem);',
    '  letter-spacing:0.12em;text-align:center;text-shadow:0 0 18px #ff2bd6,0 4px 12px #000;opacity:0;transition:opacity 0.3s;}'
  ].join('\\n');
  document.head.appendChild(st);
  (document.body || document.documentElement).appendChild(root);
  F.dom = {
    hp: document.getElementById('maze-hp-bar'),
    text: document.getElementById('maze-hud-text'),
    hurt: document.getElementById('maze-hurt'),
    muzzle: document.getElementById('maze-muzzle'),
    banner: document.getElementById('maze-banner'),
    root: root,
  };
}

function fpsStartMusic() {
  if (F.musicStarted) return;
  // Wait until splash is dismissed (or absent)
  if (document.getElementById('arcade-splash')) return;
  F.musicStarted = true;
  try {
    var amb = new Audio('./sfx/ambient-dungeon-loop.mp3');
    amb.loop = true; amb.volume = 0.22;
    var p1 = amb.play(); if (p1 && p1.catch) p1.catch(function(){});
    F.audio._ambient = amb;
    var mood = new Audio('./sfx/mood-dungeon-theme.mp3');
    mood.loop = true; mood.volume = 0.14;
    var p2 = mood.play(); if (p2 && p2.catch) p2.catch(function(){});
    F.audio._mood = mood;
  } catch (e) {}
}

function fpsCellOpen(x, y) {
  var c = Math.floor(x / F.cs);
  var r = Math.floor(y / F.cs);
  return !!F.open[c + ',' + r];
}

function fpsTryMove(st, nx, ny) {
  // Simple radius check against walls using open cells
  var rad = 28;
  if (fpsCellOpen(nx, ny) && fpsCellOpen(nx + rad, ny) && fpsCellOpen(nx - rad, ny)
      && fpsCellOpen(nx, ny + rad) && fpsCellOpen(nx, ny - rad)) {
    st.cx = nx; st.cy = ny;
    return true;
  }
  // Slide axes
  if (fpsCellOpen(nx, st.cy) && fpsCellOpen(nx + rad, st.cy) && fpsCellOpen(nx - rad, st.cy)) {
    st.cx = nx; return true;
  }
  if (fpsCellOpen(st.cx, ny) && fpsCellOpen(st.cx, ny + rad) && fpsCellOpen(st.cx, ny - rad)) {
    st.cy = ny; return true;
  }
  return false;
}

function fpsFacing() {
  var ang = runtimeScene.getScene().getVariables().get('CameraAngle').getAsNumber();
  // Character forwardAngle = CameraAngle - 90; vel = (cos fa, sin fa)
  var fa = (ang - 90) * Math.PI / 180;
  return { ang: ang, fx: Math.cos(fa), fy: Math.sin(fa) };
}

function fpsPlayerPos() {
  var players = runtimeScene.getObjects('Player');
  if (!players.length) return null;
  var p = players[0];
  return {
    x: p.getCenterX ? p.getCenterX() : (p.getX() + p.getWidth() / 2),
    y: p.getCenterY ? p.getCenterY() : (p.getY() + p.getHeight() / 2),
    z: p.getZ ? p.getZ() : 0,
    obj: p,
  };
}

function fpsCountAlive() {
  var n = 0;
  for (var id in F.enemyState) {
    if (F.enemyState.hasOwnProperty(id) && F.enemyState[id].alive) n++;
  }
  return n;
}

function fpsUpdateHud() {
  fpsEnsureHud();
  if (!F.dom) return;
  var pct = Math.max(0, Math.min(1, F.hp / F.maxHp));
  F.dom.hp.style.width = (pct * 100).toFixed(1) + '%';
  F.dom.hp.style.background = pct > 0.5
    ? 'linear-gradient(90deg,#2a2,#8f4)'
    : pct > 0.25
      ? 'linear-gradient(90deg,#e82,#fc4)'
      : 'linear-gradient(90deg,#e22,#f84)';
  var weapon = F.fireCd > 0 ? 'COOLING' : 'READY';
  F.dom.text.innerHTML =
    'HP ' + Math.max(0, Math.ceil(F.hp)) + '/' + F.maxHp +
    '&nbsp;&nbsp;\\uD83D\\uDD2B ' + weapon + '<br>' +
    'GEMS ' + F.gems + '/' + F.totalGems +
    '&nbsp;&nbsp;KEYS ' + F.keys +
    '&nbsp;&nbsp;FOES ' + fpsCountAlive() +
    '<br><span style="opacity:0.75;font-size:11px">WASD move · Q/E strafe · SPACE/CTRL fire · SHIFT run</span>';
  F.dom.hurt.style.opacity = String(Math.max(0, Math.min(0.85, F.hurtFlash)));
  F.dom.muzzle.style.opacity = F.muzzle > 0 ? String(Math.min(1, F.muzzle * 4)) : '0';
  // Screen shake via canvas parent
  try {
    var canvas = document.querySelector('canvas');
    if (canvas && canvas.parentElement) {
      var sh = F.shake > 0 ? (Math.random() - 0.5) * 10 * F.shake : 0;
      var sv = F.shake > 0 ? (Math.random() - 0.5) * 8 * F.shake : 0;
      canvas.parentElement.style.transform = 'translate(' + sh.toFixed(1) + 'px,' + sv.toFixed(1) + 'px)';
    }
  } catch (e) {}
}

function fpsHurtPlayer(amount) {
  if (F.dead || F.won) return;
  F.hp -= amount;
  F.hurtFlash = 0.55;
  F.shake = 0.35;
  fpsSfx('player-hurt', 0.6);
  if (F.hp <= 0) {
    F.hp = 0;
    F.dead = true;
    fpsEnsureHud();
    if (F.dom) {
      F.dom.banner.style.opacity = '1';
      F.dom.banner.innerHTML = 'YOU DIED<br><span style="font-size:0.45em;letter-spacing:0.2em">PRESS R TO RESTART</span>';
    }
  }
}

function fpsWin() {
  if (F.won || F.dead) return;
  F.won = true;
  fpsEnsureHud();
  if (F.dom) {
    F.dom.banner.style.opacity = '1';
    F.dom.banner.innerHTML = 'DUNGEON CLEARED<br><span style="font-size:0.45em;letter-spacing:0.18em">ALL GEMS COLLECTED · SCORE ' + F.score + '</span>';
  }
  fpsSfx('ui-start', 0.5);
}

function fpsSpawnSplat(x, y, z) {
  // DOM particles near crosshair aren't ideal in 3D; use short-lived scale flash on enemy instead.
  // Also push a lightweight record for optional future use.
  F.particles.push({ t: 0.25, x: x, y: y, z: z });
}

function fpsKillEnemy(st) {
  st.alive = false;
  st.hp = 0;
  F.score += st.def.boss ? 500 : 100;
  fpsSfx('enemy-death', 0.7);
  try {
    if (st.obj) st.obj.deleteFromScene(runtimeScene);
  } catch (e) {
    try { if (st.obj) st.obj.hide(); } catch (e2) {}
  }
  st.obj = null;
}

// ── Restart ──────────────────────────────────────────────────────────
if (F.dead && gdjs.evtTools.input.wasKeyJustPressed(runtimeScene, 'r')) {
  try { runtimeScene.getGame().getSceneStack().replace('Maze'); } catch (e) {
    try { window.location.reload(); } catch (e2) {}
  }
}

fpsStartMusic();
fpsEnsureHud();

var player = fpsPlayerPos();
if (!player) { fpsUpdateHud(); }
else if (!F.dead && !F.won) {
  var face = fpsFacing();

  // ── Fire (Space / Ctrl) ──────────────────────────────────────────
  var firePressed =
    gdjs.evtTools.input.isKeyPressed(runtimeScene, 'Space') ||
    gdjs.evtTools.input.isKeyPressed(runtimeScene, 'LControl') ||
    gdjs.evtTools.input.isKeyPressed(runtimeScene, 'RControl');
  if (firePressed && F.fireCd <= 0) {
    F.fireCd = F.fireCooldown;
    F.muzzle = 0.12;
    F.shake = 0.18;
    fpsSfx('gunshot-wolf', 0.55);

    // Hitscan: closest living enemy roughly in front within range
    var best = null;
    var bestDist = F.gunRange;
    for (var hid in F.enemyState) {
      if (!F.enemyState.hasOwnProperty(hid)) continue;
      var est = F.enemyState[hid];
      if (!est.alive) continue;
      var edx = est.cx - player.x;
      var edy = est.cy - player.y;
      var dist = Math.sqrt(edx * edx + edy * edy);
      if (dist < 20 || dist > F.gunRange) continue;
      var inv = 1 / dist;
      var dot = (edx * inv) * face.fx + (edy * inv) * face.fy;
      // ~12° cone at long range, wider up close
      var need = dist < 150 ? 0.55 : 0.88;
      if (dot < need) continue;
      if (dist < bestDist) { bestDist = dist; best = est; }
    }
    if (best) {
      best.hp -= F.gunDamage;
      best.flash = 0.15;
      fpsSfx('enemy-hit', 0.65);
      fpsSpawnSplat(best.cx, best.cy, best.wz + 40);
      // Punch scale for feedback
      try {
        if (best.obj && best.obj.setScale) best.obj.setScale(1.15);
      } catch (e) {}
      if (best.hp <= 0) fpsKillEnemy(best);
    }
  }

  // ── Enemy AI ─────────────────────────────────────────────────────
  for (var aid in F.enemyState) {
    if (!F.enemyState.hasOwnProperty(aid)) continue;
    var st = F.enemyState[aid];
    if (!st.alive || !st.obj) continue;
    var def = st.def;
    if (st.atkCd > 0) st.atkCd -= dt;
    if (st.flash > 0) {
      st.flash -= dt;
      if (st.flash <= 0) {
        try { if (st.obj.setScale) st.obj.setScale(1); } catch (e) {}
      }
    }

    var dx = player.x - st.cx;
    var dy = player.y - st.cy;
    var dist = Math.sqrt(dx * dx + dy * dy) || 1;
    var aggroed = dist < def.aggro;

    // Wander / chase
    var spd = def.speed * (aggroed ? 1.0 : 0.45);
    if (def.float) spd *= 0.7;
    var mx = 0, my = 0;
    if (aggroed) {
      mx = (dx / dist) * spd * dt;
      my = (dy / dist) * spd * dt;
      // Face player (GDevelop angle on XY)
      try { st.obj.setAngle(Math.atan2(dy, dx) * 180 / Math.PI); } catch (e) {}
    } else {
      st.wanderT -= dt;
      if (st.wanderT <= 0) {
        st.wanderT = 1.5 + Math.random() * 2.5;
        var a = Math.random() * Math.PI * 2;
        st.wdx = Math.cos(a);
        st.wdy = Math.sin(a);
      }
      mx = st.wdx * spd * dt;
      my = st.wdy * spd * dt;
      try { st.obj.setAngle(Math.atan2(st.wdy, st.wdx) * 180 / Math.PI); } catch (e) {}
    }
    fpsTryMove(st, st.cx + mx, st.cy + my);

    // Bob / float
    st.bobPhase += dt * (def.float ? 1.6 : 2.4);
    var bob = def.float
      ? (def.baseZ || 70) + 28 * Math.abs(Math.sin(st.bobPhase))
      : (def.baseZ || 0) + 4 * Math.sin(st.bobPhase);
    st.wz = bob;

    // Apply transform (Model3D origin BottomCenterZ → set position of bottom-left-ish via setX/Y)
    try {
      var ow = st.obj.getWidth();
      var oh = st.obj.getHeight();
      st.obj.setX(st.cx - ow / 2);
      st.obj.setY(st.cy - oh / 2);
      if (st.obj.setZ) st.obj.setZ(st.wz);
    } catch (e) {}

    // Melee
    var mRange = def.meleeRange || 70;
    if (dist < mRange && st.atkCd <= 0) {
      st.atkCd = def.boss ? 0.9 : 1.1;
      fpsHurtPlayer(def.damage || 10);
    }

    // Beholder roar
    if (def.roar && aggroed && F.roarCd <= 0 && dist < def.aggro * 0.85) {
      F.roarCd = 6 + Math.random() * 4;
      fpsSfx('beholder-roar', 0.7);
    }
  }

  // ── Pickups: gems ────────────────────────────────────────────────
  var gems = runtimeScene.getObjects('Gem') || [];
  for (var gi = gems.length - 1; gi >= 0; gi--) {
    var g = gems[gi];
    var gx = g.getCenterX ? g.getCenterX() : (g.getX() + g.getWidth() / 2);
    var gy = g.getCenterY ? g.getCenterY() : (g.getY() + g.getHeight() / 2);
    var gdx = gx - player.x;
    var gdy = gy - player.y;
    if (gdx * gdx + gdy * gdy < 55 * 55) {
      F.gems += 1;
      F.score += 50;
      fpsSfx('pickup-gem', 0.55);
      try { g.deleteFromScene(runtimeScene); } catch (e) { try { g.hide(); } catch (e2) {} }
      if (F.gems >= F.totalGems && F.totalGems > 0) fpsWin();
    }
  }

  // ── Pickups: keys ────────────────────────────────────────────────
  var keys = runtimeScene.getObjects('Key') || [];
  for (var ki = keys.length - 1; ki >= 0; ki--) {
    var k = keys[ki];
    var kx = k.getCenterX ? k.getCenterX() : (k.getX() + k.getWidth() / 2);
    var ky = k.getCenterY ? k.getCenterY() : (k.getY() + k.getHeight() / 2);
    var kdx = kx - player.x;
    var kdy = ky - player.y;
    if (kdx * kdx + kdy * kdy < 55 * 55) {
      F.keys += 1;
      F.score += 75;
      fpsSfx('pickup-key', 0.6);
      try {
        runtimeScene.getScene().getVariables().get('HasKey').setNumber(F.keys);
      } catch (e) {}
      try { k.deleteFromScene(runtimeScene); } catch (e) { try { k.hide(); } catch (e2) {} }
    }
  }

  // ── Doors ────────────────────────────────────────────────────────
  if (F.keys > 0) {
    var doors = runtimeScene.getObjects('Door') || [];
    for (var di = doors.length - 1; di >= 0; di--) {
      var d = doors[di];
      var dx2 = (d.getCenterX ? d.getCenterX() : (d.getX() + d.getWidth() / 2)) - player.x;
      var dy2 = (d.getCenterY ? d.getCenterY() : (d.getY() + d.getHeight() / 2)) - player.y;
      if (dx2 * dx2 + dy2 * dy2 < 130 * 130) {
        F.keys -= 1;
        try {
          runtimeScene.getScene().getVariables().get('HasKey').setNumber(F.keys);
        } catch (e) {}
        fpsSfx('door-open', 0.7);
        try { d.deleteFromScene(runtimeScene); } catch (e) { try { d.hide(); } catch (e2) {} }
      }
    }
  }
}

// Keep particles list trimmed
if (F.particles.length) {
  for (var pi = F.particles.length - 1; pi >= 0; pi--) {
    F.particles[pi].t -= dt;
    if (F.particles[pi].t <= 0) F.particles.splice(pi, 1);
  }
}

fpsUpdateHud();

// Sync legacy GDevelop HUD text (hidden under our DOM HUD, still updated)
try {
  var hudObjs = runtimeScene.getObjects('HUD');
  if (hudObjs.length) {
    var label = F.dead ? 'YOU DIED — press R' : (F.won ? 'DUNGEON CLEARED!' :
      ('HP ' + Math.ceil(F.hp) + '  Gems ' + F.gems + '/' + F.totalGems + '  Keys ' + F.keys + '  Foes ' + fpsCountAlive()));
    if (hudObjs[0].setString) hudObjs[0].setString(label);
  }
} catch (e) {}
`.trim();
}

// ─── Prop & light fixture objects (3D Models) ────────────────────────────

function makeModel3DObject(name, glbFile, materialType = 'KeepOriginal', opts = {}) {
  return {
    assetStoreId: '', name, type: 'Scene3D::Model3DObject',
    updateIfNotVisible: false, variables: [], effects: [],
    behaviors: opts.behaviors || [],
    content: {
      width: 100, height: 100, depth: 100,
      rotationX: opts.rotationX || 0, rotationY: opts.rotationY || 0, rotationZ: opts.rotationZ || 0,
      keepAspectRatio: false,
      modelResourceName: glbFile,
      materialType,
      originLocation: 'BottomCenterZ',
      centerLocation: 'ObjectCenter',
      animations: opts.animations || [],
      isCastingShadow: opts.castShadow !== false,
      isReceivingShadow: opts.receiveShadow !== false,
      crossfadeDuration: 0,
    },
  };
}

function makeStaticModel3DObject(name, glbFile, materialType = 'KeepOriginal') {
  return makeModel3DObject(name, glbFile, materialType, {
    behaviors: [makeStaticPhysicsBody()],
  });
}

function makeEmissiveModel3DObject(name, glbFile) {
  return makeModel3DObject(name, glbFile, 'KeepOriginal', {
    castShadow: false,
    receiveShadow: false,
  });
}

// ─── Minimap objects ──────────────────────────────────────────────────────

function makeMinimapSpriteObject(name, imageName) {
  return {
    assetStoreId: '', name, type: 'Sprite',
    updateIfNotVisible: false, variables: [], effects: [], behaviors: [],
    animations: [{
      name: 'default', useMultipleDirections: false,
      directions: [{
        looping: false, timeBetweenFrames: 0.08,
        sprites: [{
          hasCustomCollisionMask: false, image: imageName,
          points: [],
          originPoint: { name: 'origine', x: 0, y: 0 },
          centerPoint: { automatic: true, name: 'centre', x: 0, y: 0 },
          customCollisionMask: [],
        }],
      }],
    }],
  };
}

// Initial camera angle to face the spawn direction
function spawnAngleToCameraAngle(spawnAngle) {
  // spawnAngle: 0=east(+X), 90=south(+Y in grid), etc.
  // Our camera: CameraAngle=0 → looks north (-Y in GD), CameraAngle=90 → looks east (+X)
  return spawnAngle;
}

// ─── Lighting & prop generation from grid ─────────────────────────────────

function generateLightFixtures(level) {
  const { grid, settings, areas } = level;
  const cs = settings.cellSize;
  const fixtures = [];
  let uid = 0;

  for (let r = 0; r < grid.length; r++) {
    for (let c = 0; c < grid[0].length; c++) {
      if (!isOpen(grid, r, c)) continue;
      const ch = grid[r][c];
      const area = areas[ch];
      if (!area?.lighting) continue;

      const { pattern, spacing, color } = area.lighting;
      const floorH = getFloorHeight(level, r, c);
      const ceilH = getCeilingHeight(level, r, c);

      // Place lights at spacing intervals — checkerboard pattern ensures
      // narrow 1-cell corridors still get lights (unlike grid-aligned placement)
      if ((r + c) % spacing !== 0) continue;

      const cx = c * cs + cs / 2;
      const cy = r * cs + cs / 2;
      const rgb = hexToRgb(color || '#ffffff');

      if (pattern === 'ceiling') {
        // Ceiling-mounted light panel
        fixtures.push({
          type: 'ceiling_light', id: `clight-${uid++}`,
          x: cx - 30, y: cy - 30, z: ceilH - 5,
          width: 60, height: 60, depth: 4,
          r: rgb.r, g: rgb.g, b: rgb.b,
        });
      } else if (pattern === 'sconces') {
        // Wall-mounted sconces/torches: place on walls adjacent to this cell
        const sconceZ = floorH + (ceilH - floorH) * 0.6;
        const sw = 30;  // width along wall
        const sd = 25;  // depth (protrudes from wall)
        const sh = 50;  // height (tall torch)
        // Check each direction for a wall
        if (!isOpen(grid, r - 1, c)) {
          fixtures.push({
            type: 'sconce', id: `sconce-${uid++}`,
            x: cx - sw / 2, y: r * cs, z: sconceZ,
            width: sw, height: sd, depth: sh,
            r: rgb.r, g: rgb.g, b: rgb.b,
          });
        }
        if (!isOpen(grid, r + 1, c)) {
          fixtures.push({
            type: 'sconce', id: `sconce-${uid++}`,
            x: cx - sw / 2, y: (r + 1) * cs - sd, z: sconceZ,
            width: sw, height: sd, depth: sh,
            r: rgb.r, g: rgb.g, b: rgb.b,
          });
        }
        if (!isOpen(grid, r, c - 1)) {
          fixtures.push({
            type: 'sconce', id: `sconce-${uid++}`,
            x: c * cs, y: cy - sw / 2, z: sconceZ,
            width: sd, height: sw, depth: sh,
            r: rgb.r, g: rgb.g, b: rgb.b,
          });
        }
        if (!isOpen(grid, r, c + 1)) {
          fixtures.push({
            type: 'sconce', id: `sconce-${uid++}`,
            x: (c + 1) * cs - sd, y: cy - sw / 2, z: sconceZ,
            width: sd, height: sw, depth: sh,
            r: rgb.r, g: rgb.g, b: rgb.b,
          });
        }
      }
    }
  }

  return fixtures;
}

function generateProps(level) {
  const { settings, grid } = level;
  const cs = settings.cellSize;
  const props = [];
  let uid = 0;
  // Enemy models are placed via enemies[] so combat AI owns them.
  const skipProps = new Set(['beholder', 'gargoyle', 'pacman']);

  if (!level.propPlacements) return props;

  for (const p of level.propPlacements) {
    if (skipProps.has(String(p.prop).toLowerCase())) continue;
    const gr = Math.floor(p.gy);
    const gc = Math.floor(p.gx);
    const floorH = isOpen(grid, gr, gc) ? getFloorHeight(level, gr, gc) : 0;

    if (p.prop === 'barrel') {
      props.push({
        type: 'barrel', id: `barrel-${uid++}`,
        x: p.gx * cs - 20, y: p.gy * cs - 20, z: floorH,
        width: 40, height: 40, depth: 55,
      });
    } else if (p.prop === 'crate') {
      const stack = p.stack || 1;
      for (let s = 0; s < stack; s++) {
        props.push({
          type: 'crate', id: `crate-${uid++}`,
          x: p.gx * cs - 25, y: p.gy * cs - 25, z: floorH + s * 45,
          width: 50, height: 50, depth: 45,
        });
      }
    } else if (p.prop === 'computer') {
      props.push({
        type: 'computer', id: `computer-${uid++}`,
        x: p.gx * cs - 45, y: p.gy * cs - 30, z: floorH,
        width: 90, height: 60, depth: 120,
      });
    } else {
      // Generic prop from catalog — use collision dimensions from level.json
      const def = level.props?.[p.prop];
      if (def) {
        const w = def.width || def.radius * 2 || 80;
        const d = def.depth || def.radius * 2 || 80;
        const h = def.height || 80;
        props.push({
          type: p.prop, id: `${p.prop}-${uid++}`,
          x: p.gx * cs - w / 2, y: p.gy * cs - d / 2, z: floorH,
          width: w, height: d, depth: h,
        });
      }
    }
  }

  return props;
}

function hexToRgb(hex) {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return { r, g, b };
}

// ─── Events generation ───────────────────────────────────────────────────

function generateEvents(level) {
  const { settings, spawn } = level;
  const cs = settings.cellSize;
  const spawnX = spawn.gx * cs;
  const spawnZ = spawn.gy * cs;
  const spawnAngle = spawn.angle || 0;
  const turnSpeed = settings.turnSpeed || 120;

  const events = [];

  // Scene start: position camera, set initial state
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [{ type: { value: 'DepartScene' }, parameters: [''] }],
    actions: [
      // Hide the player cube (camera IS the player)
      { type: { value: 'Cache' }, parameters: ['Player', ''] },
      // DOM HUD replaces the Text object — keep it hidden
      { type: { value: 'Cache' }, parameters: ['HUD', ''] },
      // Set initial rotation variable
      { type: { value: 'SetNumberVariable' }, parameters: ['CameraAngle', '=', `${spawnAngleToCameraAngle(spawnAngle)}`] },
      { type: { value: 'SetNumberVariable' }, parameters: ['Gems', '=', '0'] },
      { type: { value: 'SetNumberVariable' }, parameters: ['HasKey', '=', '0'] },
      { type: { value: 'TextObject::String' }, parameters: ['HUD', '=', '"HP 100  Gems 0  [WASD move, SPACE fire, SHIFT run]"'] },
    ],
  });

  // Camera follows player every frame
  // Physics3D: X,Y = ground plane, Z = vertical (up)
  // Camera Z = eye level (player Z + most of player depth)
  // Camera must look along Y axis (grid forward) — default Three.js looks along -Z,
  // so we set rotationX = -90 to tilt camera to look along +Y, with +Z as visual up
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [],
    actions: [
      { type: { value: 'SetCameraX' }, parameters: ['', '=', 'Player.CenterX()', '', '0'] },
      { type: { value: 'SetCameraY' }, parameters: ['', '=', 'Player.CenterY()', '', '0'] },
      { type: { value: 'Scene3D::SetCameraZ' }, parameters: ['', '=', 'Player.Z() + Player.Depth() * 0.8', '', '0'] },
      { type: { value: 'Scene3D::SetCameraRotationX' }, parameters: ['', '=', '90', '', '0'] },
      { type: { value: 'SetCameraAngle' }, parameters: ['', '=', 'Variable(CameraAngle)', '', '0'] },
    ],
  });

  // Every frame: sync player's forward angle to camera angle
  // Use PhysicsCharacter3D::SetForwardAngle (Scene3D::SetRotationY isn't exported properly)
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [],
    actions: [
      { type: { value: 'Physics3D::PhysicsCharacter3D::SetForwardAngle' }, parameters: ['Player', 'PhysicsCharacter3D', '=', 'Variable(CameraAngle) - 90'] },
    ],
  });

  // Forward (W / Up)
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [{ type: { value: 'BuiltinCommonInstructions::Or' }, parameters: [],
      subInstructions: [
        { type: { value: 'KeyPressed' }, parameters: ['', 'w'] },
        { type: { value: 'KeyPressed' }, parameters: ['', 'Up'] },
      ],
    }],
    actions: [
      { type: { value: 'Physics3D::PhysicsCharacter3D::SimulateForwardKey' }, parameters: ['Player', 'PhysicsCharacter3D'] },
    ],
  });

  // Backward (S / Down)
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [{ type: { value: 'BuiltinCommonInstructions::Or' }, parameters: [],
      subInstructions: [
        { type: { value: 'KeyPressed' }, parameters: ['', 's'] },
        { type: { value: 'KeyPressed' }, parameters: ['', 'Down'] },
      ],
    }],
    actions: [
      { type: { value: 'Physics3D::PhysicsCharacter3D::SimulateBackwardKey' }, parameters: ['Player', 'PhysicsCharacter3D'] },
    ],
  });

  // Turn left (A / Left)
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [{ type: { value: 'BuiltinCommonInstructions::Or' }, parameters: [],
      subInstructions: [
        { type: { value: 'KeyPressed' }, parameters: ['', 'a'] },
        { type: { value: 'KeyPressed' }, parameters: ['', 'Left'] },
      ],
    }],
    actions: [
      { type: { value: 'SetNumberVariable' }, parameters: ['CameraAngle', '-', `${turnSpeed} * TimeDelta()`] },
    ],
  });

  // Turn right (D / Right)
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [{ type: { value: 'BuiltinCommonInstructions::Or' }, parameters: [],
      subInstructions: [
        { type: { value: 'KeyPressed' }, parameters: ['', 'd'] },
        { type: { value: 'KeyPressed' }, parameters: ['', 'Right'] },
      ],
    }],
    actions: [
      { type: { value: 'SetNumberVariable' }, parameters: ['CameraAngle', '+', `${turnSpeed} * TimeDelta()`] },
    ],
  });

  // Strafe left (Q)
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [{ type: { value: 'KeyPressed' }, parameters: ['', 'q'] }],
    actions: [
      { type: { value: 'Physics3D::PhysicsCharacter3D::SimulateLeftKey' }, parameters: ['Player', 'PhysicsCharacter3D'] },
    ],
  });

  // Strafe right (E)
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [{ type: { value: 'KeyPressed' }, parameters: ['', 'e'] }],
    actions: [
      { type: { value: 'Physics3D::PhysicsCharacter3D::SimulateRightKey' }, parameters: ['Player', 'PhysicsCharacter3D'] },
    ],
  });

  // Jump moved off Space (Space = FIRE). Optional keyboard jump on F.
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [{ type: { value: 'KeyPressed' }, parameters: ['', 'f'] }],
    actions: [
      { type: { value: 'Physics3D::PhysicsCharacter3D::SimulateJumpKey' }, parameters: ['Player', 'PhysicsCharacter3D'] },
    ],
  });

  // Wolfenstein-style combat, roaming AI, pickups, doors, DOM HUD, SFX, music
  events.push({
    type: 'BuiltinCommonInstructions::JsCode',
    inlineCode: generateCombatJs(level),
    parameterObjects: '',
    useStrict: true,
    eventsSheetExpanded: false,
  });

  // All lights are steady — no flickering (point lights from level areas provide ambient glow)

  // Sprint (Shift) — increase forward speed
  const sprintSpeed = (settings.moveSpeed || 200) * 2;
  const normalSpeed = settings.moveSpeed || 200;
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [{ type: { value: 'BuiltinCommonInstructions::Or' }, parameters: [],
        subInstructions: [
          { type: { value: 'KeyPressed' }, parameters: ['', 'LShift'] },
          { type: { value: 'KeyPressed' }, parameters: ['', 'RShift'] },
        ] }],
    actions: [
      { type: { value: 'Physics3D::PhysicsCharacter3D::SetForwardSpeedMax' }, parameters: ['Player', 'PhysicsCharacter3D', '=', `${sprintSpeed}`] },
    ],
  });
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [{ type: { value: 'BuiltinCommonInstructions::Not' }, parameters: [],
      subInstructions: [
        { type: { value: 'BuiltinCommonInstructions::Or' }, parameters: [],
        subInstructions: [
          { type: { value: 'KeyPressed' }, parameters: ['', 'LShift'] },
          { type: { value: 'KeyPressed' }, parameters: ['', 'RShift'] },
        ] },
      ],
    }],
    actions: [
      { type: { value: 'Physics3D::PhysicsCharacter3D::SetForwardSpeedMax' }, parameters: ['Player', 'PhysicsCharacter3D', '=', `${normalSpeed}`] },
    ],
  });

  // ── Minimap positioning ─────────────────────────────────────────────
  if (MINIMAP) {
    const ppu = MINIMAP.pxPerCell / cs;  // pixels per game unit
    const mapCX = MINIMAP.mapWidth / 2;
    const mapCY = MINIMAP.mapHeight / 2;
    const pad = MINIMAP.padding;
    const mr = MINIMAP.minimapRadius;
    const margin = 20;
    const ringHalf = MINIMAP.ringSize / 2;
    const dotHalf = MINIMAP.dotSize / 2;

    // Screen position of minimap center (lower-right corner)
    const mmCX = `SceneWindowWidth() - ${margin + mr}`;
    const mmCY = `SceneWindowHeight() - ${margin + mr}`;

    // dx = (padding + Player.CenterX() * ppu) - mapCenterX
    const dxExpr = `(${pad} + Player.CenterX() * ${ppu} - ${mapCX})`;
    const dyExpr = `(${pad} + Player.CenterY() * ${ppu} - ${mapCY})`;

    // angle in radians (negative camera angle for rotation)
    const angExpr = `ToRad(0 - Variable(CameraAngle))`;

    // Sprite X = minimapCX - mapCenterX - dx*cos(a) + dy*sin(a)
    const mapXExpr = `(${mmCX}) - ${mapCX} - ${dxExpr} * cos(${angExpr}) + ${dyExpr} * sin(${angExpr})`;
    const mapYExpr = `(${mmCY}) - ${mapCY} - ${dxExpr} * sin(${angExpr}) - ${dyExpr} * cos(${angExpr})`;

    // Every frame: position minimap sprites
    events.push({
      type: 'BuiltinCommonInstructions::Standard',
      conditions: [],
      actions: [
        // Position and rotate the map
        { type: { value: 'MettreX' }, parameters: ['MinimapMap', '=', mapXExpr] },
        { type: { value: 'MettreY' }, parameters: ['MinimapMap', '=', mapYExpr] },
        { type: { value: 'SetAngle' }, parameters: ['MinimapMap', '=', `0 - Variable(CameraAngle)`] },
        // Center the ring over the minimap viewport
        { type: { value: 'MettreX' }, parameters: ['MinimapRing', '=', `(${mmCX}) - ${ringHalf}`] },
        { type: { value: 'MettreY' }, parameters: ['MinimapRing', '=', `(${mmCY}) - ${ringHalf}`] },
        // Player dot: fixed at minimap center
        { type: { value: 'MettreX' }, parameters: ['MinimapDot', '=', `(${mmCX}) - ${dotHalf}`] },
        { type: { value: 'MettreY' }, parameters: ['MinimapDot', '=', `(${mmCY}) - ${dotHalf}`] },
      ],
    });

    // JavaScript event: apply a circular Pixi.js mask to the map sprite
    // with a feathered (alpha gradient) edge. Runs every frame to update
    // the mask position as the window resizes.
    const feather = 15;
    events.push({
      type: 'BuiltinCommonInstructions::JsCode',
      inlineCode: [
        `var mapObjs = runtimeScene.getObjects("MinimapMap");`,
        `if (mapObjs.length > 0) {`,
        `  var mapObj = mapObjs[0];`,
        `  var renderer = mapObj.getRendererObject();`,
        `  var w = runtimeScene.getGame().getGameResolutionWidth();`,
        `  var h = runtimeScene.getGame().getGameResolutionHeight();`,
        `  var cx = w - ${margin + mr};`,
        `  var cy = h - ${margin + mr};`,
        `  var r = ${mr};`,
        `  var feather = ${feather};`,
        `  if (!renderer._minimapMask) {`,
        `    var g = new PIXI.Graphics();`,
        `    renderer._minimapMask = g;`,
        `    renderer.parent.addChild(g);`,
        `    renderer.mask = g;`,
        `  }`,
        `  var g = renderer._minimapMask;`,
        `  g.clear();`,
        `  g.beginFill(0xffffff, 1.0);`,
        `  g.drawCircle(cx, cy, r);`,
        `  g.endFill();`,
        `}`,
        '',
      ],
      parameterObjects: '',
      useStrict: true,
      eventsSheetExpanded: false,
    });
  }

  return events;
}

// ─── Layer effects ───────────────────────────────────────────────────────

function generateLayerEffects(level) {
  const effects = [];
  const s = level.settings;

  effects.push({
    effectType: 'Scene3D::AmbientLight',
    name: 'AmbientLight',
    doubleParameters: { intensity: s.ambientLight?.intensity ?? 0.3 },
    stringParameters: { color: s.ambientLight?.color || '#222233' },
    booleanParameters: {},
  });

  effects.push({
    effectType: 'Scene3D::DirectionalLight',
    name: 'DirectionalLight',
    doubleParameters: {
      intensity: s.directionalLight?.intensity ?? 0.5,
      elevation: s.directionalLight?.elevation ?? 60,
      rotation: s.directionalLight?.rotation ?? 45,
      distanceFromCamera: 1500,
      frustumSize: 4000,
    },
    stringParameters: {
      color: s.directionalLight?.color || '#8888aa',
      top: 'Y-',
      shadowQuality: 'medium',
    },
    booleanParameters: {
      isCastingShadow: s.directionalLight?.castShadow ?? true,
    },
  });

  if (s.fog) {
    if (s.fog.type === 'linear') {
      effects.push({
        effectType: 'Scene3D::LinearFog',
        name: 'Fog',
        doubleParameters: { near: s.fog.near ?? 200, far: s.fog.far ?? 2000 },
        stringParameters: { color: s.fog.color || '#0a0a15' },
        booleanParameters: {},
      });
    } else {
      effects.push({
        effectType: 'Scene3D::ExponentialFog',
        name: 'Fog',
        doubleParameters: { density: s.fog.density ?? 0.002 },
        stringParameters: { color: s.fog.color || '#0a0a15' },
        booleanParameters: {},
      });
    }
  }

  return effects;
}

// ─── Assemble game.json ──────────────────────────────────────────────────

function compile(level) {
  const { settings, grid } = level;
  const cs = settings.cellSize;

  // Generate geometry
  const geometry = generateGeometry(level);

  // Collect unique object definitions needed
  const objectDefs = new Map();
  for (const g of geometry) {
    const key = `${g.type}_${g.texture}`;
    if (!objectDefs.has(key)) {
      const name = `${capitalize(g.type)}_${g.texture}`;
      if (g.type === 'floor') objectDefs.set(key, makeFloorObject(g.texture, g.materialType));
      else if (g.type === 'ceiling') objectDefs.set(key, makeCeilingObject(g.texture, g.materialType));
      else objectDefs.set(key, makeWallObject(g.texture, g.materialType));
      objectDefs.get(key).name = name;
    }
  }

  // Generate light fixtures and props
  const lightFixtures = generateLightFixtures(level);
  const props = generateProps(level);

  // Add prop object types (3D models)
  const barrelObj = makeStaticModel3DObject('Barrel', 'barrel.glb');
  const crateObj = makeStaticModel3DObject('Crate', 'crate.glb');
  const computerObj = makeModel3DObject('Computer', 'computer.glb', 'KeepOriginal', {
    behaviors: [makeStaticPhysicsBody()],
    animations: [{ name: 'blink', source: 'blink', loop: true }],
  });
  // Enemies: no static physics — combat JS drives position
  const pacmanObj = makeEnemyModelObject('Pacman', 'pacman.glb');
  const gargoyleObj = makeEnemyModelObject('Gargoyle', 'gargoyle.glb');
  const beholderObj = makeEnemyModelObject('Beholder', 'beholder.glb');
  const angelObj = makeModel3DObject('Angel', 'angel.glb', 'KeepOriginal', {
    behaviors: [makeStaticPhysicsBody()], rotationX: 90,
  });
  // Light fixtures: emissive materials baked into GLB
  const sconceObj = makeEmissiveModel3DObject('Sconce', 'sconce.glb');
  const ceilingLightObj = makeEmissiveModel3DObject('CeilingLight', 'ceiling_light.glb');


  // Add player, HUD, Gem, Key, Door objects
  const playerObj = makePlayerObject(settings);
  const hudObj = makeHUDObject();
  const gemObj = makeGemObject();
  const keyObj = makeKeyObject();
  const doorObj = makeDoorObject();

  // Minimap objects (HUD layer sprites)
  const minimapObjects = [];
  if (MINIMAP) {
    minimapObjects.push(
      makeMinimapSpriteObject('MinimapMap', 'minimap.png'),
      makeMinimapSpriteObject('MinimapRing', 'minimap_ring.png'),
      makeMinimapSpriteObject('MinimapDot', 'minimap_dot.png'),
    );
  }

  const allObjects = [
    ...objectDefs.values(), playerObj, hudObj, gemObj, keyObj, doorObj,
    barrelObj, crateObj, computerObj, pacmanObj, gargoyleObj, beholderObj, angelObj,
    sconceObj, ceilingLightObj,
    ...minimapObjects,
  ];

  // Generate instances
  const instances = [];
  for (const g of geometry) {
    const key = `${g.type}_${g.texture}`;
    const objName = objectDefs.get(key).name;
    instances.push({
      angle: g.angle || 0,
      customSize: true,
      width: g.width,
      height: g.height,
      layer: '',
      name: objName,
      x: g.x,
      y: g.y,
      zOrder: g.type === 'floor' ? 0 : g.type === 'ceiling' ? 0 : 1,
      z: g.z,
      depth: g.depth,
      numberProperties: [],
      stringProperties: [],
      initialVariables: [],
      persistentUuid: g.id,
    });
  }

  // Player instance at spawn — start above floor so physics drops us down
  const spawnFloor = getFloorHeight(level, Math.floor(level.spawn.gy), Math.floor(level.spawn.gx));
  instances.push({
    angle: 0, customSize: true, width: 30, height: 30,
    depth: 120,
    layer: '', name: 'Player',
    x: level.spawn.gx * cs - 15,
    y: level.spawn.gy * cs - 15,
    z: spawnFloor + 10,
    zOrder: 5,
    numberProperties: [], stringProperties: [], initialVariables: [],
    persistentUuid: 'player-1',
  });

  // HUD instance
  instances.push({
    angle: 0, customSize: false, width: 0, height: 0,
    layer: 'HUDLayer', name: 'HUD',
    x: 16, y: 16, z: 0, zOrder: 10,
    numberProperties: [], stringProperties: [], initialVariables: [],
    persistentUuid: 'hud-1',
  });

  // Minimap instances (positioned by events every frame)
  if (MINIMAP) {
    instances.push({
      angle: 0, customSize: true,
      width: MINIMAP.mapWidth, height: MINIMAP.mapHeight,
      layer: 'HUDLayer', name: 'MinimapMap',
      x: 0, y: 0, z: 0, zOrder: 20,
      numberProperties: [], stringProperties: [], initialVariables: [],
      persistentUuid: 'minimap-map',
    });
    instances.push({
      angle: 0, customSize: true,
      width: MINIMAP.ringSize, height: MINIMAP.ringSize,
      layer: 'HUDLayer', name: 'MinimapRing',
      x: 0, y: 0, z: 0, zOrder: 22,
      numberProperties: [], stringProperties: [], initialVariables: [],
      persistentUuid: 'minimap-mask',
    });
    instances.push({
      angle: 0, customSize: true,
      width: MINIMAP.dotSize, height: MINIMAP.dotSize,
      layer: 'HUDLayer', name: 'MinimapDot',
      x: 0, y: 0, z: 0, zOrder: 21,
      numberProperties: [], stringProperties: [], initialVariables: [],
      persistentUuid: 'minimap-dot',
    });
  }

  // Collectible instances (gems + keys)
  if (level.collectibles) {
    for (let i = 0; i < level.collectibles.length; i++) {
      const col = level.collectibles[i];
      if (col.type !== 'gem' && col.type !== 'key') continue;
      const gr = Math.floor(col.gy);
      const gc = Math.floor(col.gx);
      const fh = getFloorHeight(level, gr, gc);
      const objName = col.type === 'key' ? 'Key' : 'Gem';
      instances.push({
        angle: 0, customSize: false, width: 0, height: 0,
        layer: '', name: objName,
        x: col.gx * cs, y: col.gy * cs, z: fh + 50,
        zOrder: 2,
        numberProperties: [], stringProperties: [], initialVariables: [],
        persistentUuid: `${col.type}-${i}`,
      });
    }
  }

  // Door instances (locked gates — combat JS deletes when player has a key)
  if (level.doors) {
    for (let i = 0; i < level.doors.length; i++) {
      const d = level.doors[i];
      const gr = Math.floor(d.gy);
      const gc = Math.floor(d.gx);
      const fh = isOpen(grid, gr, gc) ? getFloorHeight(level, gr, gc) : 0;
      const thickness = d.thickness || 24;
      const height = d.height || 220;
      const width = d.width || 180;
      const ew = (d.orientation || 'ew') === 'ew';
      // ew door spans X (blocks north-south passage); ns door spans Y
      const w = ew ? width : thickness;
      const h = ew ? thickness : width;
      instances.push({
        angle: 0, customSize: true,
        width: w, height: h, depth: height,
        layer: '', name: 'Door',
        x: d.gx * cs - w / 2,
        y: d.gy * cs - h / 2,
        z: fh,
        zOrder: 3,
        numberProperties: [], stringProperties: [], initialVariables: [],
        persistentUuid: d.id || `door-${i}`,
      });
    }
  }

  // Enemy instances (from enemies[] — not propPlacements)
  if (level.enemies) {
    const enemyDims = {
      beholder: { w: 100, h: 100, d: 100 },
      gargoyle: { w: 70, h: 70, d: 90 },
      pacman: { w: 80, h: 80, d: 60 },
    };
    for (let i = 0; i < level.enemies.length; i++) {
      const e = level.enemies[i];
      const type = String(e.type || 'beholder').toLowerCase();
      const dims = enemyDims[type] || { w: 80, h: 80, d: 80 };
      const gr = Math.floor(e.gy);
      const gc = Math.floor(e.gx);
      const fh = isOpen(grid, gr, gc) ? getFloorHeight(level, gr, gc) : 0;
      const baseZ = e.baseZ ?? (type === 'beholder' ? 70 : fh);
      instances.push({
        angle: 0, customSize: true,
        width: dims.w, height: dims.h, depth: dims.d,
        layer: '', name: capitalize(type),
        x: e.gx * cs - dims.w / 2,
        y: e.gy * cs - dims.h / 2,
        z: baseZ,
        zOrder: 4,
        numberProperties: [], stringProperties: [], initialVariables: [],
        persistentUuid: `enemy-${type}-${i}`,
      });
    }
  }

  // Light fixture instances
  for (const lf of lightFixtures) {
    const objName = lf.type === 'sconce' ? 'Sconce' : 'CeilingLight';
    instances.push({
      angle: 0, customSize: true,
      width: lf.width, height: lf.height, depth: lf.depth,
      layer: '', name: objName,
      x: lf.x, y: lf.y, z: lf.z, zOrder: 3,
      numberProperties: [], stringProperties: [], initialVariables: [],
      persistentUuid: lf.id,
    });
  }

  // Prop instances (skip enemy types — those come from enemies[])
  const enemyTypes = new Set(['beholder', 'gargoyle', 'pacman']);
  for (const p of props) {
    if (enemyTypes.has(String(p.type).toLowerCase())) continue;
    const objName = capitalize(p.type);
    instances.push({
      angle: 0, customSize: true,
      width: p.width, height: p.height, depth: p.depth,
      layer: '', name: objName,
      x: p.x, y: p.y, z: p.z, zOrder: 2,
      numberProperties: [], stringProperties: [], initialVariables: [],
      persistentUuid: p.id,
    });
  }

  // Collect all texture files used
  const resources = [];
  const textureFiles = new Set();
  for (const mat of Object.values(level.materials)) {
    for (const key of ['wall', 'floor', 'ceiling']) {
      if (mat[key]) textureFiles.add(`${mat[key]}.png`);
    }
  }
  textureFiles.add('gem.png');
  textureFiles.add('key.png');
  if (existsSync(join(__dirname, 'loading.png'))) textureFiles.add('loading.png');

  for (const file of textureFiles) {
    resources.push({
      file, kind: 'image', metadata: '', name: file,
      smoothed: false, userAdded: true,
    });
  }

  // Minimap resources
  if (MINIMAP) {
    for (const file of ['minimap.png', 'minimap_ring.png', 'minimap_dot.png']) {
      resources.push({
        file, kind: 'image', metadata: '', name: file,
        smoothed: true, userAdded: true,
      });
    }
  }

  // 3D model resources (GLB files for props)
  const modelFiles = ['barrel.glb', 'crate.glb', 'computer.glb', 'sconce.glb', 'ceiling_light.glb', 'pacman.glb', 'gargoyle.glb', 'beholder.glb', 'angel.glb'];
  for (const file of modelFiles) {
    resources.push({
      file, kind: 'model3D', metadata: '', name: file,
      userAdded: true,
    });
  }

  // Parse background color
  const bgColor = settings.backgroundColor || '#0a0a15';
  const bgR = parseInt(bgColor.slice(1, 3), 16);
  const bgG = parseInt(bgColor.slice(3, 5), 16);
  const bgB = parseInt(bgColor.slice(5, 7), 16);

  // Build game.json
  const gameJson = {
    firstLayout: 'Maze',
    gdVersion: { build: 237, major: 5, minor: 5, revision: 0 },
    properties: {
      adaptGameResolutionAtRuntime: true,
      antialiasingMode: 'MSAA',
      antialisingEnabledOnMobile: false,
      folderProject: false,
      orientation: 'landscape',
      packageName: 'com.grassvalley.mazeexplorer',
      pixelsRounding: false,
      projectUuid: 'c3d4e5f6-a7b8-9012-cdef-345678901234',
      scaleMode: 'linear',
      sizeOnStartupMode: 'adaptWidth',
      templateSlug: '',
      version: '1.0.0',
      name: 'Maze Explorer',
      description: 'Wolfenstein-style dungeon FPS — roam, shoot, loot gems. Pink Horse of Whimsy.',
      author: 'Pink Horse of Whimsy',
      windowWidth: 800,
      windowHeight: 600,
      latestCompilationDirectory: '',
      maxFPS: 60, minFPS: 20, verticalSync: false,
      platformSpecificAssets: {},
      loadingScreen: {
        backgroundColor: (bgR << 16) | (bgG << 8) | bgB,
        backgroundFadeInDuration: 0.2,
        backgroundImageResourceName: existsSync(join(__dirname, 'loading.png')) ? 'loading.png' : '',
        gdevelopLogoStyle: 'light',
        logoAndProgressColor: 16777215,
        logoAndProgressLogoAndProgressFadeInDelay: 0.2,
        progressBarColor: 16777215,
        progressBarHeight: 20,
        progressBarMaxWidth: 200,
        progressBarMinWidth: 40,
        progressBarWidthPercent: 30,
        showGDevelopSplash: false,
        showProgressBar: true,
      },
      watermark: { placement: 'bottom-left', showWatermark: true },
      authorIds: [], authorUsernames: [], categories: [],
      playableDevices: ['keyboard'],
      extensionProperties: [],
      platforms: [{ name: 'GDevelop JS platform' }],
      currentPlatform: 'GDevelop JS platform',
    },
    resources: { resources, resourceFolders: [] },
    objects: [],
    objectsFolderStructure: { folderName: '__ROOT', children: [] },
    objectsGroups: [],
    variables: [],
    layouts: [{
      b: bgB, r: bgR, v: bgG,
      disableInputWhenNotFocused: true,
      mangledName: 'Maze', name: 'Maze',
      standardSortMethod: true,
      stopSoundsOnStartup: true,
      title: '',
      uiSettings: {
        grid: true, gridType: 'rectangular',
        gridWidth: settings.cellSize, gridHeight: settings.cellSize,
        gridOffsetX: 0, gridOffsetY: 0, gridColor: 10401023, gridAlpha: 0.8,
        snap: true, zoomFactor: 0.15, windowMask: false,
      },
      objectsGroups: [],
      variables: [
        { name: 'Gems', type: 'number', value: 0 },
        { name: 'HasKey', type: 'number', value: 0 },
        { name: 'CameraAngle', type: 'number', value: 0 },
      ],
      instances,
      objects: allObjects,
      objectsFolderStructure: {
        folderName: '__ROOT',
        children: allObjects.map(o => ({ objectName: o.name })),
      },
      events: generateEvents(level),
      layers: [
        {
          ambientLightColorB: 40, ambientLightColorG: 40, ambientLightColorR: 50,
          camera3DFarPlaneDistance: 10000,
          camera3DFieldOfView: 70,
          camera3DNearPlaneDistance: 3,
          followBaseLayerCamera: false,
          isLightingLayer: false, isLocked: false,
          name: '', renderingType: '2d+3d', visibility: true,
          cameras: [{
            defaultSize: true, defaultViewport: true, height: 0,
            viewportBottom: 1, viewportLeft: 0, viewportRight: 1, viewportTop: 0, width: 0,
          }],
          effects: generateLayerEffects(level),
        },
        {
          ambientLightColorB: 128, ambientLightColorG: 128, ambientLightColorR: 128,
          camera3DFarPlaneDistance: 10000,
          camera3DFieldOfView: 45,
          camera3DNearPlaneDistance: 3,
          followBaseLayerCamera: false,
          isLightingLayer: false, isLocked: false,
          name: 'HUDLayer', renderingType: '2d', visibility: true,
          cameras: [{
            defaultSize: true, defaultViewport: true, height: 0,
            viewportBottom: 1, viewportLeft: 0, viewportRight: 1, viewportTop: 0, width: 0,
          }],
          effects: [],
        },
      ],
      behaviorsSharedData: [
        {
          name: 'Physics3D',
          type: 'Physics3D::Physics3DBehavior',
          content: {
            gravityX: 0,
            gravityY: 0,
            gravityZ: -9.8,
            worldScale: 100,
          },
        },
      ],
    }],
    externalEvents: [],
    eventsFunctionsExtensions: [],
    externalLayouts: [],
    externalSourceFiles: [],
  };

  return gameJson;
}

function capitalize(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// ─── Main ────────────────────────────────────────────────────────────────

const levelPath = process.argv[2] || join(__dirname, 'level.json');
const outPath = process.argv[3] || join(__dirname, 'game.json');

console.log(`Compiling level: ${levelPath}`);
const level = loadLevel(levelPath);

const gridRows = level.grid.length;
const gridCols = level.grid[0].length;
const openCells = level.grid.flat().join('').replace(/#/g, '').length;
console.log(`  Grid: ${gridCols}x${gridRows}, ${openCells} open cells`);

const gameJson = compile(level);
const instanceCount = gameJson.layouts[0].instances.length;
const objectCount = gameJson.layouts[0].objects.length;

writeFileSync(outPath, JSON.stringify(gameJson, null, 2));
console.log(`  Generated: ${objectCount} object types, ${instanceCount} instances`);
console.log(`  Output: ${outPath}`);
