#!/usr/bin/env node

/**
 * Level compiler: transforms level.json into GDevelop game.json.
 *
 * Usage: node compile-level.mjs [level.json] [game.json]
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Minimap config (generated by generate-minimap.mjs)
const minimapConfigPath = join(__dirname, 'minimap-config.json');
const MINIMAP = existsSync(minimapConfigPath)
  ? JSON.parse(readFileSync(minimapConfigPath, 'utf8'))
  : null;

// ─── Load & validate level ───────────────────────────────────────────────

function loadLevel(path) {
  const level = JSON.parse(readFileSync(path, 'utf8'));
  validate(level);
  return level;
}

function validate(level) {
  const { grid, areas, spawn } = level;
  if (!grid || !grid.length) throw new Error('Grid is empty');

  const width = grid[0].length;
  for (let r = 0; r < grid.length; r++) {
    if (grid[r].length !== width)
      throw new Error(`Grid row ${r} has length ${grid[r].length}, expected ${width}`);
  }

  // Check borders are solid
  for (let c = 0; c < width; c++) {
    if (grid[0][c] !== '#') throw new Error(`Top border not solid at col ${c}`);
    if (grid[grid.length - 1][c] !== '#') throw new Error(`Bottom border not solid at col ${c}`);
  }
  for (let r = 0; r < grid.length; r++) {
    if (grid[r][0] !== '#') throw new Error(`Left border not solid at row ${r}`);
    if (grid[r][width - 1] !== '#') throw new Error(`Right border not solid at row ${r}`);
  }

  // Check all area characters are defined
  for (let r = 0; r < grid.length; r++) {
    for (let c = 0; c < width; c++) {
      const ch = grid[r][c];
      if (ch !== '#' && !areas[ch])
        throw new Error(`Grid char '${ch}' at (${r},${c}) not defined in areas`);
    }
  }

  // Check spawn is on open cell
  const sr = Math.floor(spawn.gy);
  const sc = Math.floor(spawn.gx);
  if (grid[sr]?.[sc] === '#')
    throw new Error(`Spawn at (${spawn.gx},${spawn.gy}) is inside a wall`);
}

// ─── Geometry generation ─────────────────────────────────────────────────

function isOpen(grid, r, c) {
  return r >= 0 && r < grid.length && c >= 0 && c < grid[0].length && grid[r][c] !== '#';
}

function getFloorHeight(level, r, c) {
  const ch = level.grid[r][c];
  const area = level.areas[ch];
  const baseHeight = area?.floorHeight || 0;
  if (level.heights && level.heights[r] && level.heights[r][c] !== undefined) {
    return baseHeight + level.heights[r][c];
  }
  return baseHeight;
}

function getCeilingHeight(level, r, c) {
  const ch = level.grid[r][c];
  const area = level.areas[ch];
  return area?.ceilingHeight || level.settings.wallHeight;
}

function getMaterial(level, r, c) {
  const ch = level.grid[r][c];
  const area = level.areas[ch];
  const matName = area?.material || 'dungeon';
  return level.materials[matName];
}

/**
 * Generate all geometry instances from the grid.
 *
 * Coordinate convention (matching GDevelop Physics3D / Jolt):
 *   X = left/right (grid columns)
 *   Y = forward/back (grid rows)
 *   Z = up/down (vertical — gravity pulls -Z)
 *
 * GDevelop object properties:
 *   width  = X extent
 *   height = Y extent
 *   depth  = Z extent (vertical)
 */
function generateGeometry(level) {
  const { grid, settings } = level;
  const cs = settings.cellSize;
  const wt = settings.wallThickness;
  const rows = grid.length;
  const cols = grid[0].length;
  const instances = [];
  let uid = 0;

  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      if (!isOpen(grid, r, c)) continue;

      const mat = getMaterial(level, r, c);
      const floorH = getFloorHeight(level, r, c);
      const ceilH = getCeilingHeight(level, r, c);
      const wallH = ceilH - floorH;

      // Floor slab (thin horizontal at floor level)
      instances.push({
        type: 'floor', id: `floor-${uid++}`,
        x: c * cs, y: r * cs, z: floorH,
        width: cs, height: cs, depth: wt,
        texture: mat.floor,
        materialType: mat.materialType,
      });

      // Ceiling slab (thin horizontal at ceiling level)
      instances.push({
        type: 'ceiling', id: `ceil-${uid++}`,
        x: c * cs, y: r * cs, z: floorH + wallH,
        width: cs, height: cs, depth: wt,
        texture: mat.ceiling,
        materialType: mat.materialType,
      });

      // North wall (border with r-1): thin in Y, tall in Z
      if (!isOpen(grid, r - 1, c)) {
        instances.push({
          type: 'wall', id: `wall-${uid++}`,
          x: c * cs, y: r * cs, z: floorH,
          width: cs, height: wt, depth: wallH,
          texture: mat.wall, materialType: mat.materialType,
        });
      }

      // South wall (border with r+1)
      if (!isOpen(grid, r + 1, c)) {
        instances.push({
          type: 'wall', id: `wall-${uid++}`,
          x: c * cs, y: (r + 1) * cs - wt, z: floorH,
          width: cs, height: wt, depth: wallH,
          texture: mat.wall, materialType: mat.materialType,
        });
      }

      // West wall (border with c-1): thin in X, tall in Z
      if (!isOpen(grid, r, c - 1)) {
        instances.push({
          type: 'wall', id: `wall-${uid++}`,
          x: c * cs, y: r * cs, z: floorH,
          width: wt, height: cs, depth: wallH,
          texture: mat.wall, materialType: mat.materialType,
        });
      }

      // East wall (border with c+1)
      if (!isOpen(grid, r, c + 1)) {
        instances.push({
          type: 'wall', id: `wall-${uid++}`,
          x: (c + 1) * cs - wt, y: r * cs, z: floorH,
          width: wt, height: cs, depth: wallH,
          texture: mat.wall, materialType: mat.materialType,
        });
      }

      // Note: height transitions between adjacent cells are handled by the
      // character controller's stairHeightMax — no step walls needed.
    }
  }

  return instances;
}

// ─── Object definitions ──────────────────────────────────────────────────

function makeStaticPhysicsBody() {
  return {
    name: 'Physics3D',
    type: 'Physics3D::Physics3DBehavior',
    content: {
      object3D: '',
      bodyType: 'Static',
      bullet: false,
      fixedRotation: false,
      shape: 'Box',
      meshShapeResourceName: '',
      shapeOrientation: 'Z',
      shapeDimensionA: 0, shapeDimensionB: 0, shapeDimensionC: 0,
      shapeOffsetX: 0, shapeOffsetY: 0, shapeOffsetZ: 0,
      massCenterOffsetX: 0, massCenterOffsetY: 0, massCenterOffsetZ: 0,
      massOverride: 0,
      density: 1.0,
      friction: 0.5,
      restitution: 0.0,
      linearDamping: 0.1,
      angularDamping: 0.1,
      gravityScale: 1,
      layers: 17,
      masks: 17,
    },
  };
}

function makeWallObject(textureName, materialType) {
  return {
    assetStoreId: '', name: `Wall_${textureName}`, type: 'Scene3D::Cube3DObject',
    updateIfNotVisible: false, variables: [], effects: [],
    behaviors: [makeStaticPhysicsBody()],
    content: {
      width: 100, height: 100, depth: 100,
      ...makeCubeFaces(textureName),
      enableTextureTransparency: false,
      materialType: materialType || 'StandardWithoutMetalness',
    },
  };
}

function makeFloorObject(textureName, materialType) {
  return {
    assetStoreId: '', name: `Floor_${textureName}`, type: 'Scene3D::Cube3DObject',
    updateIfNotVisible: false, variables: [], effects: [],
    behaviors: [makeStaticPhysicsBody()],
    content: {
      width: 100, height: 100, depth: 100,
      ...makeCubeFaces(textureName),
      enableTextureTransparency: false,
      materialType: materialType || 'StandardWithoutMetalness',
    },
  };
}

function makeCeilingObject(textureName, materialType) {
  return {
    assetStoreId: '', name: `Ceiling_${textureName}`, type: 'Scene3D::Cube3DObject',
    updateIfNotVisible: false, variables: [], effects: [],
    behaviors: [makeStaticPhysicsBody()],
    content: {
      width: 100, height: 100, depth: 100,
      ...makeCubeFaces(textureName),
      enableTextureTransparency: false,
      materialType: materialType || 'StandardWithoutMetalness',
    },
  };
}

function makeCubeFaces(textureName) {
  const faces = {};
  for (const face of ['front', 'back', 'left', 'right', 'top', 'bottom']) {
    faces[`${face}FaceResourceName`] = `${textureName}.png`;
    faces[`${face}FaceVisible`] = true;
    faces[`${face}FaceResourceRepeat`] = true;
  }
  return faces;
}

function makePlayerObject(settings) {
  return {
    assetStoreId: '', name: 'Player', type: 'Scene3D::Cube3DObject',
    updateIfNotVisible: false, variables: [], effects: [],
    behaviors: [
      {
        name: 'Physics3D',
        type: 'Physics3D::Physics3DBehavior',
        content: {
          object3D: '',
          bodyType: 'Dynamic',
          bullet: false,
          fixedRotation: true,
          shape: 'Capsule',
          meshShapeResourceName: '',
          shapeOrientation: 'Z',
          shapeDimensionA: 0, shapeDimensionB: 0, shapeDimensionC: 0,
          shapeOffsetX: 0, shapeOffsetY: 0, shapeOffsetZ: 0,
          massCenterOffsetX: 0, massCenterOffsetY: 0, massCenterOffsetZ: 0,
          massOverride: 0,
          density: 1.0,
          friction: 0.5,
          restitution: 0.0,
          linearDamping: 0.1,
          angularDamping: 0.1,
          gravityScale: 1,
          layers: 17,
          masks: 17,
        },
      },
      {
        name: 'PhysicsCharacter3D',
        type: 'Physics3D::PhysicsCharacter3D',
        content: {
          physics3D: 'Physics3D',
          jumpHeight: settings.jumpSpeed || 150,
          jumpSustainTime: 0.2,
          gravity: settings.gravity || 800,
          fallingSpeedMax: 700,
          forwardAcceleration: 1200,
          forwardDeceleration: 1200,
          forwardSpeedMax: settings.moveSpeed || 200,
          sidewaysAcceleration: 800,
          sidewaysDeceleration: 800,
          sidewaysSpeedMax: settings.strafeSpeed || 150,
          slopeMaxAngle: 50,
          stairHeightMax: settings.stepHeight || 60,
          shouldBindObjectAndForwardAngle: false,
          canBePushed: false,
        },
      },
    ],
    content: {
      width: 30, height: 30, depth: 120,
      frontFaceResourceName: '', backFaceResourceName: '',
      leftFaceResourceName: '', rightFaceResourceName: '',
      topFaceResourceName: '', bottomFaceResourceName: '',
      frontFaceVisible: false, backFaceVisible: false,
      leftFaceVisible: false, rightFaceVisible: false,
      topFaceVisible: false, bottomFaceVisible: false,
      frontFaceResourceRepeat: false, backFaceResourceRepeat: false,
      leftFaceResourceRepeat: false, rightFaceResourceRepeat: false,
      topFaceResourceRepeat: false, bottomFaceResourceRepeat: false,
      enableTextureTransparency: false,
      materialType: 'Basic',
    },
  };
}

function makeHUDObject() {
  return {
    assetStoreId: '', name: 'HUD', type: 'TextObject::Text',
    updateIfNotVisible: false, variables: [], effects: [], behaviors: [],
    characterSize: 24, font: '', textAlignment: 'left',
    color: { b: 255, g: 255, r: 255 }, string: 'Gems: 0',
    bold: true, italic: false, underlined: false, smoothed: true,
    isOutlineEnabled: true, outlineColor: { b: 0, g: 0, r: 0 }, outlineThickness: 2,
    isShadowEnabled: false, shadowColor: { b: 0, g: 0, r: 0 },
    shadowOpacity: 127, shadowDistance: 1, shadowAngle: 90, shadowBlurRadius: 1,
  };
}

function makeGemObject() {
  return {
    assetStoreId: '', name: 'Gem', type: 'Sprite',
    updateIfNotVisible: false, variables: [], effects: [], behaviors: [],
    animations: [{
      name: 'idle', useMultipleDirections: false,
      directions: [{
        looping: true, timeBetweenFrames: 0.08,
        sprites: [{
          hasCustomCollisionMask: false, image: 'gem.png',
          points: [],
          originPoint: { name: 'origine', x: 0, y: 0 },
          centerPoint: { automatic: true, name: 'centre', x: 0, y: 0 },
          customCollisionMask: [],
        }],
      }],
    }],
  };
}

// ─── Prop & light fixture objects (3D Models) ────────────────────────────

function makeModel3DObject(name, glbFile, materialType = 'KeepOriginal', opts = {}) {
  return {
    assetStoreId: '', name, type: 'Scene3D::Model3DObject',
    updateIfNotVisible: false, variables: [], effects: [],
    behaviors: opts.behaviors || [],
    content: {
      width: 100, height: 100, depth: 100,
      rotationX: opts.rotationX || 0, rotationY: opts.rotationY || 0, rotationZ: opts.rotationZ || 0,
      keepAspectRatio: false,
      modelResourceName: glbFile,
      materialType,
      originLocation: 'BottomCenterZ',
      centerLocation: 'ObjectCenter',
      animations: opts.animations || [],
      isCastingShadow: opts.castShadow !== false,
      isReceivingShadow: opts.receiveShadow !== false,
      crossfadeDuration: 0,
    },
  };
}

function makeStaticModel3DObject(name, glbFile, materialType = 'KeepOriginal') {
  return makeModel3DObject(name, glbFile, materialType, {
    behaviors: [makeStaticPhysicsBody()],
  });
}

function makeEmissiveModel3DObject(name, glbFile) {
  return makeModel3DObject(name, glbFile, 'KeepOriginal', {
    castShadow: false,
    receiveShadow: false,
  });
}

// ─── Minimap objects ──────────────────────────────────────────────────────

function makeMinimapSpriteObject(name, imageName) {
  return {
    assetStoreId: '', name, type: 'Sprite',
    updateIfNotVisible: false, variables: [], effects: [], behaviors: [],
    animations: [{
      name: 'default', useMultipleDirections: false,
      directions: [{
        looping: false, timeBetweenFrames: 0.08,
        sprites: [{
          hasCustomCollisionMask: false, image: imageName,
          points: [],
          originPoint: { name: 'origine', x: 0, y: 0 },
          centerPoint: { automatic: true, name: 'centre', x: 0, y: 0 },
          customCollisionMask: [],
        }],
      }],
    }],
  };
}

// Initial camera angle to face the spawn direction
function spawnAngleToCameraAngle(spawnAngle) {
  // spawnAngle: 0=east(+X), 90=south(+Y in grid), etc.
  // Our camera: CameraAngle=0 → looks north (-Y in GD), CameraAngle=90 → looks east (+X)
  return spawnAngle;
}

// ─── Lighting & prop generation from grid ─────────────────────────────────

function generateLightFixtures(level) {
  const { grid, settings, areas } = level;
  const cs = settings.cellSize;
  const fixtures = [];
  let uid = 0;

  for (let r = 0; r < grid.length; r++) {
    for (let c = 0; c < grid[0].length; c++) {
      if (!isOpen(grid, r, c)) continue;
      const ch = grid[r][c];
      const area = areas[ch];
      if (!area?.lighting) continue;

      const { pattern, spacing, color } = area.lighting;
      const floorH = getFloorHeight(level, r, c);
      const ceilH = getCeilingHeight(level, r, c);

      // Place lights at spacing intervals — checkerboard pattern ensures
      // narrow 1-cell corridors still get lights (unlike grid-aligned placement)
      if ((r + c) % spacing !== 0) continue;

      const cx = c * cs + cs / 2;
      const cy = r * cs + cs / 2;
      const rgb = hexToRgb(color || '#ffffff');

      if (pattern === 'ceiling') {
        // Ceiling-mounted light panel
        fixtures.push({
          type: 'ceiling_light', id: `clight-${uid++}`,
          x: cx - 30, y: cy - 30, z: ceilH - 5,
          width: 60, height: 60, depth: 4,
          r: rgb.r, g: rgb.g, b: rgb.b,
        });
      } else if (pattern === 'sconces') {
        // Wall-mounted sconces/torches: place on walls adjacent to this cell
        const sconceZ = floorH + (ceilH - floorH) * 0.6;
        const sw = 30;  // width along wall
        const sd = 25;  // depth (protrudes from wall)
        const sh = 50;  // height (tall torch)
        // Check each direction for a wall
        if (!isOpen(grid, r - 1, c)) {
          fixtures.push({
            type: 'sconce', id: `sconce-${uid++}`,
            x: cx - sw / 2, y: r * cs, z: sconceZ,
            width: sw, height: sd, depth: sh,
            r: rgb.r, g: rgb.g, b: rgb.b,
          });
        }
        if (!isOpen(grid, r + 1, c)) {
          fixtures.push({
            type: 'sconce', id: `sconce-${uid++}`,
            x: cx - sw / 2, y: (r + 1) * cs - sd, z: sconceZ,
            width: sw, height: sd, depth: sh,
            r: rgb.r, g: rgb.g, b: rgb.b,
          });
        }
        if (!isOpen(grid, r, c - 1)) {
          fixtures.push({
            type: 'sconce', id: `sconce-${uid++}`,
            x: c * cs, y: cy - sw / 2, z: sconceZ,
            width: sd, height: sw, depth: sh,
            r: rgb.r, g: rgb.g, b: rgb.b,
          });
        }
        if (!isOpen(grid, r, c + 1)) {
          fixtures.push({
            type: 'sconce', id: `sconce-${uid++}`,
            x: (c + 1) * cs - sd, y: cy - sw / 2, z: sconceZ,
            width: sd, height: sw, depth: sh,
            r: rgb.r, g: rgb.g, b: rgb.b,
          });
        }
      }
    }
  }

  return fixtures;
}

function generateProps(level) {
  const { settings, grid } = level;
  const cs = settings.cellSize;
  const props = [];
  let uid = 0;

  if (!level.propPlacements) return props;

  for (const p of level.propPlacements) {
    const gr = Math.floor(p.gy);
    const gc = Math.floor(p.gx);
    const floorH = isOpen(grid, gr, gc) ? getFloorHeight(level, gr, gc) : 0;

    if (p.prop === 'barrel') {
      props.push({
        type: 'barrel', id: `barrel-${uid++}`,
        x: p.gx * cs - 20, y: p.gy * cs - 20, z: floorH,
        width: 40, height: 40, depth: 55,
      });
    } else if (p.prop === 'crate') {
      const stack = p.stack || 1;
      for (let s = 0; s < stack; s++) {
        props.push({
          type: 'crate', id: `crate-${uid++}`,
          x: p.gx * cs - 25, y: p.gy * cs - 25, z: floorH + s * 45,
          width: 50, height: 50, depth: 45,
        });
      }
    } else if (p.prop === 'computer') {
      props.push({
        type: 'computer', id: `computer-${uid++}`,
        x: p.gx * cs - 45, y: p.gy * cs - 30, z: floorH,
        width: 90, height: 60, depth: 120,
      });
    } else {
      // Generic prop from catalog — use collision dimensions from level.json
      const def = level.props?.[p.prop];
      if (def) {
        const w = def.width || def.radius * 2 || 80;
        const d = def.depth || def.radius * 2 || 80;
        const h = def.height || 80;
        props.push({
          type: p.prop, id: `${p.prop}-${uid++}`,
          x: p.gx * cs - w / 2, y: p.gy * cs - d / 2, z: floorH,
          width: w, height: d, depth: h,
        });
      }
    }
  }

  return props;
}

function hexToRgb(hex) {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return { r, g, b };
}

// ─── Events generation ───────────────────────────────────────────────────

function generateEvents(level) {
  const { settings, spawn } = level;
  const cs = settings.cellSize;
  const spawnX = spawn.gx * cs;
  const spawnZ = spawn.gy * cs;
  const spawnAngle = spawn.angle || 0;
  const turnSpeed = settings.turnSpeed || 120;

  const events = [];

  // Scene start: position camera, set initial state
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [{ type: { value: 'DepartScene' }, parameters: [''] }],
    actions: [
      // Hide the player cube (camera IS the player)
      { type: { value: 'Cache' }, parameters: ['Player', ''] },
      // Set initial rotation variable
      { type: { value: 'SetNumberVariable' }, parameters: ['CameraAngle', '=', `${spawnAngleToCameraAngle(spawnAngle)}`] },
      { type: { value: 'SetNumberVariable' }, parameters: ['Gems', '=', '0'] },
      { type: { value: 'TextObject::String' }, parameters: ['HUD', '=', '"Gems: 0  [WASD / Arrows, Q/E strafe, Space jump, Shift run]"'] },
    ],
  });

  // Camera follows player every frame
  // Physics3D: X,Y = ground plane, Z = vertical (up)
  // Camera Z = eye level (player Z + most of player depth)
  // Camera must look along Y axis (grid forward) — default Three.js looks along -Z,
  // so we set rotationX = -90 to tilt camera to look along +Y, with +Z as visual up
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [],
    actions: [
      { type: { value: 'SetCameraX' }, parameters: ['', '=', 'Player.CenterX()', '', '0'] },
      { type: { value: 'SetCameraY' }, parameters: ['', '=', 'Player.CenterY()', '', '0'] },
      { type: { value: 'Scene3D::SetCameraZ' }, parameters: ['', '=', 'Player.Z() + Player.Depth() * 0.8', '', '0'] },
      { type: { value: 'Scene3D::SetCameraRotationX' }, parameters: ['', '=', '90', '', '0'] },
      { type: { value: 'SetCameraAngle' }, parameters: ['', '=', 'Variable(CameraAngle)', '', '0'] },
    ],
  });

  // Every frame: sync player's forward angle to camera angle
  // Use PhysicsCharacter3D::SetForwardAngle (Scene3D::SetRotationY isn't exported properly)
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [],
    actions: [
      { type: { value: 'Physics3D::PhysicsCharacter3D::SetForwardAngle' }, parameters: ['Player', 'PhysicsCharacter3D', '=', 'Variable(CameraAngle) - 90'] },
    ],
  });

  // Forward (W / Up)
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [{ type: { value: 'BuiltinCommonInstructions::Or' }, parameters: [],
      subInstructions: [
        { type: { value: 'KeyPressed' }, parameters: ['', 'w'] },
        { type: { value: 'KeyPressed' }, parameters: ['', 'Up'] },
      ],
    }],
    actions: [
      { type: { value: 'Physics3D::PhysicsCharacter3D::SimulateForwardKey' }, parameters: ['Player', 'PhysicsCharacter3D'] },
    ],
  });

  // Backward (S / Down)
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [{ type: { value: 'BuiltinCommonInstructions::Or' }, parameters: [],
      subInstructions: [
        { type: { value: 'KeyPressed' }, parameters: ['', 's'] },
        { type: { value: 'KeyPressed' }, parameters: ['', 'Down'] },
      ],
    }],
    actions: [
      { type: { value: 'Physics3D::PhysicsCharacter3D::SimulateBackwardKey' }, parameters: ['Player', 'PhysicsCharacter3D'] },
    ],
  });

  // Turn left (A / Left)
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [{ type: { value: 'BuiltinCommonInstructions::Or' }, parameters: [],
      subInstructions: [
        { type: { value: 'KeyPressed' }, parameters: ['', 'a'] },
        { type: { value: 'KeyPressed' }, parameters: ['', 'Left'] },
      ],
    }],
    actions: [
      { type: { value: 'SetNumberVariable' }, parameters: ['CameraAngle', '-', `${turnSpeed} * TimeDelta()`] },
    ],
  });

  // Turn right (D / Right)
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [{ type: { value: 'BuiltinCommonInstructions::Or' }, parameters: [],
      subInstructions: [
        { type: { value: 'KeyPressed' }, parameters: ['', 'd'] },
        { type: { value: 'KeyPressed' }, parameters: ['', 'Right'] },
      ],
    }],
    actions: [
      { type: { value: 'SetNumberVariable' }, parameters: ['CameraAngle', '+', `${turnSpeed} * TimeDelta()`] },
    ],
  });

  // Strafe left (Q)
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [{ type: { value: 'KeyPressed' }, parameters: ['', 'q'] }],
    actions: [
      { type: { value: 'Physics3D::PhysicsCharacter3D::SimulateLeftKey' }, parameters: ['Player', 'PhysicsCharacter3D'] },
    ],
  });

  // Strafe right (E)
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [{ type: { value: 'KeyPressed' }, parameters: ['', 'e'] }],
    actions: [
      { type: { value: 'Physics3D::PhysicsCharacter3D::SimulateRightKey' }, parameters: ['Player', 'PhysicsCharacter3D'] },
    ],
  });

  // Jump (Space)
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [{ type: { value: 'KeyPressed' }, parameters: ['', 'Space'] }],
    actions: [
      { type: { value: 'Physics3D::PhysicsCharacter3D::SimulateJumpKey' }, parameters: ['Player', 'PhysicsCharacter3D'] },
    ],
  });

  // Orbiting props (e.g., beholder circling a room)
  if (level.props) {
    const orbitProps = [];
    for (const [propName, def] of Object.entries(level.props)) {
      if (def.orbit) orbitProps.push({ name: capitalize(propName), orbit: def.orbit });
    }

    if (orbitProps.length > 0) {
      // Build JS code to orbit all props with bobbing
      const jsLines = [];
      jsLines.push('var dt = runtimeScene.getTimeManager().getElapsedTime() / 1000;');
      jsLines.push('if (!runtimeScene.__orbitTime) runtimeScene.__orbitTime = 0;');
      jsLines.push('runtimeScene.__orbitTime += dt;');
      jsLines.push('var t = runtimeScene.__orbitTime;');

      for (const { name, orbit } of orbitProps) {
        const cx = orbit.centerGx * cs;
        const cy = orbit.centerGy * cs;
        const r = orbit.radius;
        const speed = orbit.speed;
        const bobH = orbit.bobHeight;
        const bobSpeed = orbit.bobSpeed;
        const baseZ = orbit.baseZ || 0;

        jsLines.push(`var objs = runtimeScene.getObjects("${name}");`);
        jsLines.push(`if (objs.length > 0) {`);
        jsLines.push(`  var o = objs[0];`);
        jsLines.push(`  var angle = t * ${speed} * Math.PI * 2;`);
        jsLines.push(`  o.setX(${cx} + ${r} * Math.cos(angle) - o.getWidth() / 2);`);
        jsLines.push(`  o.setY(${cy} + ${r} * Math.sin(angle) - o.getHeight() / 2);`);
        jsLines.push(`  o.setZ(${baseZ} + ${bobH} * Math.abs(Math.sin(t * ${bobSpeed} * Math.PI * 2)));`);
        // Face direction of travel: tangent to circle
        // Tangent of CCW orbit = orbit angle + 90° in math, but GDevelop angles are CW
        jsLines.push(`  var deg = (angle * 180 / Math.PI);`);
        jsLines.push(`  o.setAngle(deg);`);
        jsLines.push(`}`);
      }

      events.push({
        type: 'BuiltinCommonInstructions::JsCode',
        inlineCode: jsLines.join('\n'),
        parameterObjects: '',
        useStrict: true,
        eventsSheetExpanded: false,
      });
    }
  }

  // All lights are steady — no flickering (point lights from level areas provide ambient glow)

  // Sprint (Shift) — increase forward speed
  const sprintSpeed = (settings.moveSpeed || 200) * 2;
  const normalSpeed = settings.moveSpeed || 200;
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [{ type: { value: 'BuiltinCommonInstructions::Or' }, parameters: [],
        subInstructions: [
          { type: { value: 'KeyPressed' }, parameters: ['', 'LShift'] },
          { type: { value: 'KeyPressed' }, parameters: ['', 'RShift'] },
        ] }],
    actions: [
      { type: { value: 'Physics3D::PhysicsCharacter3D::SetForwardSpeedMax' }, parameters: ['Player', 'PhysicsCharacter3D', '=', `${sprintSpeed}`] },
    ],
  });
  events.push({
    type: 'BuiltinCommonInstructions::Standard',
    conditions: [{ type: { value: 'BuiltinCommonInstructions::Not' }, parameters: [],
      subInstructions: [
        { type: { value: 'BuiltinCommonInstructions::Or' }, parameters: [],
        subInstructions: [
          { type: { value: 'KeyPressed' }, parameters: ['', 'LShift'] },
          { type: { value: 'KeyPressed' }, parameters: ['', 'RShift'] },
        ] },
      ],
    }],
    actions: [
      { type: { value: 'Physics3D::PhysicsCharacter3D::SetForwardSpeedMax' }, parameters: ['Player', 'PhysicsCharacter3D', '=', `${normalSpeed}`] },
    ],
  });

  // ── Minimap positioning ─────────────────────────────────────────────
  if (MINIMAP) {
    const ppu = MINIMAP.pxPerCell / cs;  // pixels per game unit
    const mapCX = MINIMAP.mapWidth / 2;
    const mapCY = MINIMAP.mapHeight / 2;
    const pad = MINIMAP.padding;
    const mr = MINIMAP.minimapRadius;
    const margin = 20;
    const ringHalf = MINIMAP.ringSize / 2;
    const dotHalf = MINIMAP.dotSize / 2;

    // Screen position of minimap center (lower-right corner)
    const mmCX = `SceneWindowWidth() - ${margin + mr}`;
    const mmCY = `SceneWindowHeight() - ${margin + mr}`;

    // dx = (padding + Player.CenterX() * ppu) - mapCenterX
    const dxExpr = `(${pad} + Player.CenterX() * ${ppu} - ${mapCX})`;
    const dyExpr = `(${pad} + Player.CenterY() * ${ppu} - ${mapCY})`;

    // angle in radians (negative camera angle for rotation)
    const angExpr = `ToRad(0 - Variable(CameraAngle))`;

    // Sprite X = minimapCX - mapCenterX - dx*cos(a) + dy*sin(a)
    const mapXExpr = `(${mmCX}) - ${mapCX} - ${dxExpr} * cos(${angExpr}) + ${dyExpr} * sin(${angExpr})`;
    const mapYExpr = `(${mmCY}) - ${mapCY} - ${dxExpr} * sin(${angExpr}) - ${dyExpr} * cos(${angExpr})`;

    // Every frame: position minimap sprites
    events.push({
      type: 'BuiltinCommonInstructions::Standard',
      conditions: [],
      actions: [
        // Position and rotate the map
        { type: { value: 'MettreX' }, parameters: ['MinimapMap', '=', mapXExpr] },
        { type: { value: 'MettreY' }, parameters: ['MinimapMap', '=', mapYExpr] },
        { type: { value: 'SetAngle' }, parameters: ['MinimapMap', '=', `0 - Variable(CameraAngle)`] },
        // Center the ring over the minimap viewport
        { type: { value: 'MettreX' }, parameters: ['MinimapRing', '=', `(${mmCX}) - ${ringHalf}`] },
        { type: { value: 'MettreY' }, parameters: ['MinimapRing', '=', `(${mmCY}) - ${ringHalf}`] },
        // Player dot: fixed at minimap center
        { type: { value: 'MettreX' }, parameters: ['MinimapDot', '=', `(${mmCX}) - ${dotHalf}`] },
        { type: { value: 'MettreY' }, parameters: ['MinimapDot', '=', `(${mmCY}) - ${dotHalf}`] },
      ],
    });

    // JavaScript event: apply a circular Pixi.js mask to the map sprite
    // with a feathered (alpha gradient) edge. Runs every frame to update
    // the mask position as the window resizes.
    const feather = 15;
    events.push({
      type: 'BuiltinCommonInstructions::JsCode',
      inlineCode: [
        `var mapObjs = runtimeScene.getObjects("MinimapMap");`,
        `if (mapObjs.length > 0) {`,
        `  var mapObj = mapObjs[0];`,
        `  var renderer = mapObj.getRendererObject();`,
        `  var w = runtimeScene.getGame().getGameResolutionWidth();`,
        `  var h = runtimeScene.getGame().getGameResolutionHeight();`,
        `  var cx = w - ${margin + mr};`,
        `  var cy = h - ${margin + mr};`,
        `  var r = ${mr};`,
        `  var feather = ${feather};`,
        `  if (!renderer._minimapMask) {`,
        `    var g = new PIXI.Graphics();`,
        `    renderer._minimapMask = g;`,
        `    renderer.parent.addChild(g);`,
        `    renderer.mask = g;`,
        `  }`,
        `  var g = renderer._minimapMask;`,
        `  g.clear();`,
        `  g.beginFill(0xffffff, 1.0);`,
        `  g.drawCircle(cx, cy, r);`,
        `  g.endFill();`,
        `}`,
        '',
      ],
      parameterObjects: '',
      useStrict: true,
      eventsSheetExpanded: false,
    });
  }

  return events;
}

// ─── Layer effects ───────────────────────────────────────────────────────

function generateLayerEffects(level) {
  const effects = [];
  const s = level.settings;

  effects.push({
    effectType: 'Scene3D::AmbientLight',
    name: 'AmbientLight',
    doubleParameters: { intensity: s.ambientLight?.intensity ?? 0.3 },
    stringParameters: { color: s.ambientLight?.color || '#222233' },
    booleanParameters: {},
  });

  effects.push({
    effectType: 'Scene3D::DirectionalLight',
    name: 'DirectionalLight',
    doubleParameters: {
      intensity: s.directionalLight?.intensity ?? 0.5,
      elevation: s.directionalLight?.elevation ?? 60,
      rotation: s.directionalLight?.rotation ?? 45,
      distanceFromCamera: 1500,
      frustumSize: 4000,
    },
    stringParameters: {
      color: s.directionalLight?.color || '#8888aa',
      top: 'Y-',
      shadowQuality: 'medium',
    },
    booleanParameters: {
      isCastingShadow: s.directionalLight?.castShadow ?? true,
    },
  });

  if (s.fog) {
    if (s.fog.type === 'linear') {
      effects.push({
        effectType: 'Scene3D::LinearFog',
        name: 'Fog',
        doubleParameters: { near: s.fog.near ?? 200, far: s.fog.far ?? 2000 },
        stringParameters: { color: s.fog.color || '#0a0a15' },
        booleanParameters: {},
      });
    } else {
      effects.push({
        effectType: 'Scene3D::ExponentialFog',
        name: 'Fog',
        doubleParameters: { density: s.fog.density ?? 0.002 },
        stringParameters: { color: s.fog.color || '#0a0a15' },
        booleanParameters: {},
      });
    }
  }

  return effects;
}

// ─── Assemble game.json ──────────────────────────────────────────────────

function compile(level) {
  const { settings, grid } = level;
  const cs = settings.cellSize;

  // Generate geometry
  const geometry = generateGeometry(level);

  // Collect unique object definitions needed
  const objectDefs = new Map();
  for (const g of geometry) {
    const key = `${g.type}_${g.texture}`;
    if (!objectDefs.has(key)) {
      const name = `${capitalize(g.type)}_${g.texture}`;
      if (g.type === 'floor') objectDefs.set(key, makeFloorObject(g.texture, g.materialType));
      else if (g.type === 'ceiling') objectDefs.set(key, makeCeilingObject(g.texture, g.materialType));
      else objectDefs.set(key, makeWallObject(g.texture, g.materialType));
      objectDefs.get(key).name = name;
    }
  }

  // Generate light fixtures and props
  const lightFixtures = generateLightFixtures(level);
  const props = generateProps(level);

  // Add prop object types (3D models)
  const barrelObj = makeStaticModel3DObject('Barrel', 'barrel.glb');
  const crateObj = makeStaticModel3DObject('Crate', 'crate.glb');
  const computerObj = makeModel3DObject('Computer', 'computer.glb', 'KeepOriginal', {
    behaviors: [makeStaticPhysicsBody()],
    animations: [{ name: 'blink', source: 'blink', loop: true }],
  });
  const pacmanObj = makeModel3DObject('Pacman', 'pacman.glb', 'KeepOriginal', {
    behaviors: [makeStaticPhysicsBody()], rotationX: 90,
  });
  const gargoyleObj = makeModel3DObject('Gargoyle', 'gargoyle.glb', 'KeepOriginal', {
    behaviors: [makeStaticPhysicsBody()], rotationX: 90,
  });
  const beholderObj = makeModel3DObject('Beholder', 'beholder.glb', 'KeepOriginal', {
    rotationX: 90,
  });
  const angelObj = makeModel3DObject('Angel', 'angel.glb', 'KeepOriginal', {
    behaviors: [makeStaticPhysicsBody()], rotationX: 90,
  });
  // Light fixtures: emissive materials baked into GLB
  const sconceObj = makeEmissiveModel3DObject('Sconce', 'sconce.glb');
  const ceilingLightObj = makeEmissiveModel3DObject('CeilingLight', 'ceiling_light.glb');


  // Add player, HUD, Gem objects
  const playerObj = makePlayerObject(settings);
  const hudObj = makeHUDObject();
  const gemObj = makeGemObject();

  // Minimap objects (HUD layer sprites)
  const minimapObjects = [];
  if (MINIMAP) {
    minimapObjects.push(
      makeMinimapSpriteObject('MinimapMap', 'minimap.png'),
      makeMinimapSpriteObject('MinimapRing', 'minimap_ring.png'),
      makeMinimapSpriteObject('MinimapDot', 'minimap_dot.png'),
    );
  }

  const allObjects = [
    ...objectDefs.values(), playerObj, hudObj, gemObj,
    barrelObj, crateObj, computerObj, pacmanObj, gargoyleObj, beholderObj, angelObj,
    sconceObj, ceilingLightObj,
    ...minimapObjects,
  ];

  // Generate instances
  const instances = [];
  for (const g of geometry) {
    const key = `${g.type}_${g.texture}`;
    const objName = objectDefs.get(key).name;
    instances.push({
      angle: g.angle || 0,
      customSize: true,
      width: g.width,
      height: g.height,
      layer: '',
      name: objName,
      x: g.x,
      y: g.y,
      zOrder: g.type === 'floor' ? 0 : g.type === 'ceiling' ? 0 : 1,
      z: g.z,
      depth: g.depth,
      numberProperties: [],
      stringProperties: [],
      initialVariables: [],
      persistentUuid: g.id,
    });
  }

  // Player instance at spawn — start above floor so physics drops us down
  const spawnFloor = getFloorHeight(level, Math.floor(level.spawn.gy), Math.floor(level.spawn.gx));
  instances.push({
    angle: 0, customSize: true, width: 30, height: 30,
    depth: 120,
    layer: '', name: 'Player',
    x: level.spawn.gx * cs - 15,
    y: level.spawn.gy * cs - 15,
    z: spawnFloor + 10,
    zOrder: 5,
    numberProperties: [], stringProperties: [], initialVariables: [],
    persistentUuid: 'player-1',
  });

  // HUD instance
  instances.push({
    angle: 0, customSize: false, width: 0, height: 0,
    layer: 'HUDLayer', name: 'HUD',
    x: 16, y: 16, z: 0, zOrder: 10,
    numberProperties: [], stringProperties: [], initialVariables: [],
    persistentUuid: 'hud-1',
  });

  // Minimap instances (positioned by events every frame)
  if (MINIMAP) {
    instances.push({
      angle: 0, customSize: true,
      width: MINIMAP.mapWidth, height: MINIMAP.mapHeight,
      layer: 'HUDLayer', name: 'MinimapMap',
      x: 0, y: 0, z: 0, zOrder: 20,
      numberProperties: [], stringProperties: [], initialVariables: [],
      persistentUuid: 'minimap-map',
    });
    instances.push({
      angle: 0, customSize: true,
      width: MINIMAP.ringSize, height: MINIMAP.ringSize,
      layer: 'HUDLayer', name: 'MinimapRing',
      x: 0, y: 0, z: 0, zOrder: 22,
      numberProperties: [], stringProperties: [], initialVariables: [],
      persistentUuid: 'minimap-mask',
    });
    instances.push({
      angle: 0, customSize: true,
      width: MINIMAP.dotSize, height: MINIMAP.dotSize,
      layer: 'HUDLayer', name: 'MinimapDot',
      x: 0, y: 0, z: 0, zOrder: 21,
      numberProperties: [], stringProperties: [], initialVariables: [],
      persistentUuid: 'minimap-dot',
    });
  }

  // Gem instances
  if (level.collectibles) {
    for (let i = 0; i < level.collectibles.length; i++) {
      const col = level.collectibles[i];
      if (col.type !== 'gem') continue;
      const gr = Math.floor(col.gy);
      const gc = Math.floor(col.gx);
      const fh = getFloorHeight(level, gr, gc);
      instances.push({
        angle: 0, customSize: false, width: 0, height: 0,
        layer: '', name: 'Gem',
        x: col.gx * cs, y: col.gy * cs, z: fh + 50,
        zOrder: 2,
        numberProperties: [], stringProperties: [], initialVariables: [],
        persistentUuid: `gem-${i}`,
      });
    }
  }

  // Light fixture instances
  for (const lf of lightFixtures) {
    const objName = lf.type === 'sconce' ? 'Sconce' : 'CeilingLight';
    instances.push({
      angle: 0, customSize: true,
      width: lf.width, height: lf.height, depth: lf.depth,
      layer: '', name: objName,
      x: lf.x, y: lf.y, z: lf.z, zOrder: 3,
      numberProperties: [], stringProperties: [], initialVariables: [],
      persistentUuid: lf.id,
    });
  }

  // Prop instances
  for (const p of props) {
    const objName = capitalize(p.type);
    instances.push({
      angle: 0, customSize: true,
      width: p.width, height: p.height, depth: p.depth,
      layer: '', name: objName,
      x: p.x, y: p.y, z: p.z, zOrder: 2,
      numberProperties: [], stringProperties: [], initialVariables: [],
      persistentUuid: p.id,
    });
  }

  // Collect all texture files used
  const resources = [];
  const textureFiles = new Set();
  for (const mat of Object.values(level.materials)) {
    for (const key of ['wall', 'floor', 'ceiling']) {
      if (mat[key]) textureFiles.add(`${mat[key]}.png`);
    }
  }
  textureFiles.add('gem.png');
  textureFiles.add('key.png');
  if (existsSync(join(__dirname, 'loading.png'))) textureFiles.add('loading.png');

  for (const file of textureFiles) {
    resources.push({
      file, kind: 'image', metadata: '', name: file,
      smoothed: false, userAdded: true,
    });
  }

  // Minimap resources
  if (MINIMAP) {
    for (const file of ['minimap.png', 'minimap_ring.png', 'minimap_dot.png']) {
      resources.push({
        file, kind: 'image', metadata: '', name: file,
        smoothed: true, userAdded: true,
      });
    }
  }

  // 3D model resources (GLB files for props)
  const modelFiles = ['barrel.glb', 'crate.glb', 'computer.glb', 'sconce.glb', 'ceiling_light.glb', 'pacman.glb', 'gargoyle.glb', 'beholder.glb', 'angel.glb'];
  for (const file of modelFiles) {
    resources.push({
      file, kind: 'model3D', metadata: '', name: file,
      userAdded: true,
    });
  }

  // Parse background color
  const bgColor = settings.backgroundColor || '#0a0a15';
  const bgR = parseInt(bgColor.slice(1, 3), 16);
  const bgG = parseInt(bgColor.slice(3, 5), 16);
  const bgB = parseInt(bgColor.slice(5, 7), 16);

  // Build game.json
  const gameJson = {
    firstLayout: 'Maze',
    gdVersion: { build: 237, major: 5, minor: 5, revision: 0 },
    properties: {
      adaptGameResolutionAtRuntime: true,
      antialiasingMode: 'MSAA',
      antialisingEnabledOnMobile: false,
      folderProject: false,
      orientation: 'landscape',
      packageName: 'com.grassvalley.mazeexplorer',
      pixelsRounding: false,
      projectUuid: 'c3d4e5f6-a7b8-9012-cdef-345678901234',
      scaleMode: 'linear',
      sizeOnStartupMode: 'adaptWidth',
      templateSlug: '',
      version: '1.0.0',
      name: 'Maze Explorer',
      description: 'A first-person 3D maze. Example project for Grass Valley Game Club.',
      author: 'Grass Valley Game Club',
      windowWidth: 800,
      windowHeight: 600,
      latestCompilationDirectory: '',
      maxFPS: 60, minFPS: 20, verticalSync: false,
      platformSpecificAssets: {},
      loadingScreen: {
        backgroundColor: (bgR << 16) | (bgG << 8) | bgB,
        backgroundFadeInDuration: 0.2,
        backgroundImageResourceName: existsSync(join(__dirname, 'loading.png')) ? 'loading.png' : '',
        gdevelopLogoStyle: 'light',
        logoAndProgressColor: 16777215,
        logoAndProgressLogoAndProgressFadeInDelay: 0.2,
        progressBarColor: 16777215,
        progressBarHeight: 20,
        progressBarMaxWidth: 200,
        progressBarMinWidth: 40,
        progressBarWidthPercent: 30,
        showGDevelopSplash: false,
        showProgressBar: true,
      },
      watermark: { placement: 'bottom-left', showWatermark: true },
      authorIds: [], authorUsernames: [], categories: [],
      playableDevices: ['keyboard'],
      extensionProperties: [],
      platforms: [{ name: 'GDevelop JS platform' }],
      currentPlatform: 'GDevelop JS platform',
    },
    resources: { resources, resourceFolders: [] },
    objects: [],
    objectsFolderStructure: { folderName: '__ROOT', children: [] },
    objectsGroups: [],
    variables: [],
    layouts: [{
      b: bgB, r: bgR, v: bgG,
      disableInputWhenNotFocused: true,
      mangledName: 'Maze', name: 'Maze',
      standardSortMethod: true,
      stopSoundsOnStartup: true,
      title: '',
      uiSettings: {
        grid: true, gridType: 'rectangular',
        gridWidth: settings.cellSize, gridHeight: settings.cellSize,
        gridOffsetX: 0, gridOffsetY: 0, gridColor: 10401023, gridAlpha: 0.8,
        snap: true, zoomFactor: 0.15, windowMask: false,
      },
      objectsGroups: [],
      variables: [
        { name: 'Gems', type: 'number', value: 0 },
        { name: 'HasKey', type: 'number', value: 0 },
        { name: 'CameraAngle', type: 'number', value: 0 },
      ],
      instances,
      objects: allObjects,
      objectsFolderStructure: {
        folderName: '__ROOT',
        children: allObjects.map(o => ({ objectName: o.name })),
      },
      events: generateEvents(level),
      layers: [
        {
          ambientLightColorB: 40, ambientLightColorG: 40, ambientLightColorR: 50,
          camera3DFarPlaneDistance: 10000,
          camera3DFieldOfView: 70,
          camera3DNearPlaneDistance: 3,
          followBaseLayerCamera: false,
          isLightingLayer: false, isLocked: false,
          name: '', renderingType: '2d+3d', visibility: true,
          cameras: [{
            defaultSize: true, defaultViewport: true, height: 0,
            viewportBottom: 1, viewportLeft: 0, viewportRight: 1, viewportTop: 0, width: 0,
          }],
          effects: generateLayerEffects(level),
        },
        {
          ambientLightColorB: 128, ambientLightColorG: 128, ambientLightColorR: 128,
          camera3DFarPlaneDistance: 10000,
          camera3DFieldOfView: 45,
          camera3DNearPlaneDistance: 3,
          followBaseLayerCamera: false,
          isLightingLayer: false, isLocked: false,
          name: 'HUDLayer', renderingType: '2d', visibility: true,
          cameras: [{
            defaultSize: true, defaultViewport: true, height: 0,
            viewportBottom: 1, viewportLeft: 0, viewportRight: 1, viewportTop: 0, width: 0,
          }],
          effects: [],
        },
      ],
      behaviorsSharedData: [
        {
          name: 'Physics3D',
          type: 'Physics3D::Physics3DBehavior',
          content: {
            gravityX: 0,
            gravityY: 0,
            gravityZ: -9.8,
            worldScale: 100,
          },
        },
      ],
    }],
    externalEvents: [],
    eventsFunctionsExtensions: [],
    externalLayouts: [],
    externalSourceFiles: [],
  };

  return gameJson;
}

function capitalize(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// ─── Main ────────────────────────────────────────────────────────────────

const levelPath = process.argv[2] || join(__dirname, 'level.json');
const outPath = process.argv[3] || join(__dirname, 'game.json');

console.log(`Compiling level: ${levelPath}`);
const level = loadLevel(levelPath);

const gridRows = level.grid.length;
const gridCols = level.grid[0].length;
const openCells = level.grid.flat().join('').replace(/#/g, '').length;
console.log(`  Grid: ${gridCols}x${gridRows}, ${openCells} open cells`);

const gameJson = compile(level);
const instanceCount = gameJson.layouts[0].instances.length;
const objectCount = gameJson.layouts[0].objects.length;

writeFileSync(outPath, JSON.stringify(gameJson, null, 2));
console.log(`  Generated: ${objectCount} object types, ${instanceCount} instances`);
console.log(`  Output: ${outPath}`);
