#!/usr/bin/env node
// Offline asset generation only: the browser never receives an API key.
import { readFile, writeFile, mkdir, access } from "node:fs/promises";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
import vm from "node:vm";

const root = dirname(fileURLToPath(import.meta.url));
const config = JSON.parse(
  await readFile(join(root, "voice-config.json"), "utf8"),
);
const context = { window: {} };
vm.createContext(context);
for (const file of ["data.js", "host.js"])
  vm.runInContext(await readFile(join(root, file), "utf8"), context);
const { QUIZ_BANK, DOLLY_SHOW } = context.window;
const jobs = [];
for (const group of Object.values(DOLLY_SHOW.lines))
  for (const line of group) jobs.push({ id: line.id, text: line.text });
for (const story of DOLLY_SHOW.stories)
  jobs.push({
    id: "story-" + story.id,
    text:
      story.title +
      ". " +
      story.text +
      (story.quote ? " Dolly said: " + story.quote : ""),
  });
for (const questions of Object.values(QUIZ_BANK))
  for (const question of questions) {
    jobs.push({ id: question.id + "-question", text: question[0] });
    jobs.push({ id: question.id + "-fact", text: question[2] });
  }
const fingerprint = (job) =>
  createHash("sha256")
    .update(
      JSON.stringify({
        text: job.text,
        voice: config.voice_id,
        model: config.model_id,
        settings: config.settings,
      }),
    )
    .digest("hex")
    .slice(0, 12);
for (const job of jobs) {
  job.hash = fingerprint(job);
  job.file = `assets/voice/${job.id}-${job.hash}.mp3`;
}
if (process.argv.includes("--dry-run")) {
  console.log(
    JSON.stringify(
      {
        clips: jobs.length,
        characters: jobs.reduce((n, j) => n + j.text.length, 0),
        voice: config.voice_name,
      },
      null,
      2,
    ),
  );
  process.exit(0);
}
const key = process.env.ELEVENLABS_API_KEY;
if (!key)
  throw new Error(
    "Set ELEVENLABS_API_KEY, or use node --env-file=<your .env path>.",
  );
const only = process.argv.find((a) => a.startsWith("--only="))?.slice(7);
const selected = only ? jobs.filter((j) => j.id.startsWith(only)) : jobs;
if (!selected.length) throw new Error("No voice jobs match --only.");
await mkdir(join(root, "assets/voice"), { recursive: true });
const exists = async (path) => {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
};
let done = 0,
  rendered = 0;
const queue = [...selected];
await Promise.all(
  Array.from({ length: 3 }, async () => {
    while (queue.length) {
      const job = queue.shift(),
        path = join(root, job.file);
      if (!(await exists(path))) {
        for (let attempt = 0; attempt < 4; attempt++) {
          const res = await fetch(
            `https://api.elevenlabs.io/v1/text-to-speech/${config.voice_id}?output_format=mp3_44100_64`,
            {
              method: "POST",
              headers: {
                "xi-api-key": key,
                "content-type": "application/json",
              },
              body: JSON.stringify({
                text: job.text,
                model_id: config.model_id,
                voice_settings: config.settings,
              }),
              signal: AbortSignal.timeout(60000),
            },
          );
          if (res.ok) {
            const bytes = Buffer.from(await res.arrayBuffer());
            if (bytes.length < 1000)
              throw new Error(`${job.id}: empty audio response`);
            await writeFile(path + ".part", bytes);
            const { rename } = await import("node:fs/promises");
            await rename(path + ".part", path);
            rendered++;
            break;
          }
          if ((res.status === 429 || res.status >= 500) && attempt < 3) {
            await res.arrayBuffer();
            await new Promise((r) => setTimeout(r, 2000 * (attempt + 1)));
            continue;
          }
          throw new Error(
            `${job.id}: ElevenLabs ${res.status}: ${(await res.text()).slice(0, 250)}`,
          );
        }
      }
      done++;
      if (done % 10 === 0 || done === selected.length)
        console.log(
          `Voice clips: ${done}/${selected.length} (${rendered} newly rendered)`,
        );
    }
  }),
);
// Publish only a complete manifest, so interrupted runs are resumable and safe.
const missing = [];
for (const job of jobs)
  if (!(await exists(join(root, job.file)))) missing.push(job.id);
if (missing.length) {
  console.log(
    `Subset ready; ${missing.length} clips remain before the full manifest can be published.`,
  );
  process.exit(0);
}
const manifest = Object.fromEntries(jobs.map(({ id, ...job }) => [id, job]));
await writeFile(
  join(root, "voice-manifest.js"),
  "// Generated by generate-voice.mjs. Content hashes keep changed clips from going stale.\nwindow.DOLLY_VOICE_MANIFEST = " +
    JSON.stringify(manifest, null, 2) +
    ";\n",
);
console.log(
  `Complete: ${jobs.length} clips. No live TTS service is required to play.`,
);
